In [2]:
import numpy as np

    Create a NumPy array containing the numbers from 1 to 20. Provide the code to create this array using NumPy.

In [4]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

    Given two NumPy arrays, arr1 and arr2, both containing integer values, perform element-wise addition and subtraction between these arrays.
    arr1 = np.array([1, 2, 3])
    arr2 = np.array([4, 5, 6])

In [5]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [6]:
arr1+arr2

array([5, 7, 9])

In [7]:
np.add(arr1,arr2)

array([5, 7, 9])

In [8]:
arr1-arr2

array([-3, -3, -3])

In [9]:
np.subtract(arr1,arr2)

array([-3, -3, -3])

    Given a NumPy array of student ages, find and print the ages of students who are older than 18.

In [10]:
ages = np.array([17, 21, 19, 25, 16, 18, 20])

In [11]:
ages>18

array([False,  True,  True,  True, False, False,  True])

In [12]:
ages[2]

19

In [13]:
ages[ages>18]

array([21, 19, 25, 20])

In [14]:
cond=ages>18
ages[cond]

array([21, 19, 25, 20])

    You have a 1D NumPy array containing the numbers from 1 to 12. Reshape it into a 3x4 2D array.

In [15]:
ar=np.arange(1,13)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
ar.ndim

1

In [17]:
ar.shape

(12,)

In [18]:
ar.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

    2x2x3

In [21]:
ar2=ar.reshape(2,2,3)
ar2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [22]:
ar2.ndim

3

In [23]:
ar.reshape(2,2,3).ndim

3

    Given a NumPy array of test scores, find the average score, the number of students who scored above 90, and the number of students who failed (scored below 60).

In [24]:
scores = np.array([85, 90, 78, 92, 88, 76, 89, 94, 81, 87])

In [35]:
np.mean(scores),scores[scores>90].size,scores[scores<60].size

(86.0, 2, 0)

In [32]:
len(scores[scores>90])

2

In [33]:
scores[scores>90].size

2

In [34]:
scores[scores<60].size

0

In [25]:
np.sum(scores)

860

In [26]:
len(scores)

10

In [27]:
np.sum(scores)/len(scores)

86.0

In [28]:
np.mean(scores)

86.0

    You have two 2D NumPy arrays, matrix1 (3x4) and matrix2 (4x2). Multiply these matrices and find the resulting matrix.

In [36]:
matrix1 = np.random.randint(1, 10, (3, 4))
matrix2 = np.random.randint(1, 10, (4, 2))

In [41]:
np.dot(matrix2,matrix1)

ValueError: shapes (4,2) and (3,4) not aligned: 2 (dim 1) != 3 (dim 0)

In [40]:
np.dot(matrix1,matrix2)

array([[155, 106],
       [109, 102],
       [171, 150]])

In [37]:
matrix1,matrix2

(array([[3, 7, 2, 8],
        [9, 1, 2, 6],
        [2, 3, 8, 9]]),
 array([[4, 4],
        [9, 2],
        [8, 8],
        [8, 8]]))

    mxn
    pxq

    n=p

    Given a 2D NumPy array representing a chessboard, extract and print the black squares.

In [42]:
chessboard = np.array([
    ['B', 'W', 'B', 'W', 'B'],
    ['W', 'B', 'W', 'B', 'W'],
    ['B', 'W', 'B', 'W', 'B'],
    ['W', 'B', 'W', 'B', 'W']
])
chessboard

array([['B', 'W', 'B', 'W', 'B'],
       ['W', 'B', 'W', 'B', 'W'],
       ['B', 'W', 'B', 'W', 'B'],
       ['W', 'B', 'W', 'B', 'W']], dtype='<U1')

    even row    00 01 02 03 04
                10 11 12 13 14
                20 21 22 23 24
    odd row     30 31 32 33 34

    00 02 04
    11 13
    20 22 24
    31 33


In [58]:
even_lst=[i for i in range(0,20,2)]
even_lst

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [59]:
odd_lst=[i for i in range(1,20,2)]
odd_lst

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [54]:
row1=chessboard[0]
row1[::2]

array(['B', 'B', 'B'], dtype='<U1')

In [60]:
chessboard[0][::2]

array(['B', 'B', 'B'], dtype='<U1')

In [56]:
row2=chessboard[1]
row2[1::2]

array(['B', 'B'], dtype='<U1')

In [62]:
for i in range(len(chessboard)):
    if i%2==0:
       print(chessboard[i][::2])
    else:
        print(chessboard[i][1::2])

['B' 'B' 'B']
['B' 'B']
['B' 'B' 'B']
['B' 'B']


    Given a 2D NumPy array representing student data with columns for age, test scores, and attendance, select students who are older than 20, scored above 85, and attended at least 90% of the classes.

In [64]:
student_data = np.array([
    [22, 90, 95],
    [19, 88, 92],
    [25, 78, 85],
    [21, 92, 91],
    [20, 86, 89]
])

    and &
    or  |
    not !

In [77]:
student_data[(student_data[:,0]>20) & (student_data[:,1]>85) | (student_data[:,2]>=92)]

array([[22, 90, 95],
       [19, 88, 92],
       [21, 92, 91]])

In [73]:
student_data[(student_data[:,0]>20) & (student_data[:,1]>85)]

array([[22, 90, 95],
       [21, 92, 91]])

In [72]:
student_data[(student_data[:,0]>20)]

array([[22, 90, 95],
       [25, 78, 85],
       [21, 92, 91]])

In [66]:
student_data[:,0]>20

array([ True, False,  True,  True, False])

In [67]:
student_data[:,1]>85

array([ True,  True, False,  True,  True])

In [68]:
student_data[:,2]>=90

array([ True,  True, False,  True, False])

array([[22, 90, 95],
       [25, 78, 85],
       [21, 92, 91]])