In [1]:
! pip install numpy

In [5]:
import numpy as np

In [3]:
np.__version__

'1.24.1'

In [3]:
import array as arr

In [1]:
lst =[1,2,3,5]

In [6]:
arr=np.array([1,2,3,4,5,6])

In [7]:
type(arr)

numpy.ndarray

In [9]:
new_list=[]
for i in list:
    new_list.append(i*2)
    
new_list

[2, 4, 6, 10]

In [2]:
list(map(lambda x:x*2,lst))

[2, 4, 6, 10]

    String
    Float
    int
    boolean

    Numpy Data types
        int32
        int64
        float32
        float64
        <U32 => string
    Numpy Functions
        np.array()
        dtype => data type
        ndim => dimension of the array
        shape => size in each dimension
        size => no of elements in the array
        len => no of elements in outer most dimension

In [48]:
len(arr6)

3

In [10]:
arr2=np.array([True,1,1.0,'ali'])
arr2

array(['True', '1', '1.0', 'ali'], dtype='<U32')

In [49]:
len(arr2)

4

In [12]:
arr2.dtype

dtype('<U32')

In [11]:
arr3=np.array([True,1,5,1.0])
arr3

array([1., 1., 5., 1.])

In [13]:
arr3.dtype

dtype('float64')

In [14]:
arr4=np.array([1,2,3,4])
arr4

array([1, 2, 3, 4])

In [15]:
arr4.dtype

dtype('int32')

In [16]:
arr5=np.array([True,False])
arr5

array([ True, False])

In [25]:
arr5.ndim

1

In [17]:
arr5.dtype

dtype('bool')

In [42]:
lst=[
    [
        [1,2,3,44,5],
        [1,2,3,4,5]
    ],
    [
        [9,2,3,4,45],
        [1,2,3,4,65]
    ],
    [
        [9,2,3,4,45],
        [1,2,3,4,65]
    ]
]

In [43]:
arr6=np.array(lst)
arr6

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [44]:
arr6.ndim

3

In [45]:
arr6.shape

(3, 2, 5)

In [46]:
arr6.size

30

In [24]:
lst[0][0][3]

44

In [23]:
lst[1][0][0]

9

In [19]:
lst[0]

[[1, 2, 3, 4], [1, 2, 3, 4]]

In [21]:
lst[1]

[[9, 2, 3, 4], [1, 2, 3, 4]]

In [51]:
arr2

array(['True', '1', '1.0', 'ali'], dtype='<U32')

In [55]:
arr2[::-1]

array(['ali', '1.0', '1', 'True'], dtype='<U32')

In [52]:
arr2.shape

(4,)

    print 3 ele
    print till 3 element
    print from 3 element
    print reverse

In [58]:
arr6

array([[[ 1,  2,  3, 44,  5],
        [ 1,  2,  3,  4,  5]],

       [[ 9,  2,  3,  4, 45],
        [ 1,  2,  3,  4, 65]],

       [[ 9,  2,  3,  4, 45],
        [ 1,  2,  3,  4, 65]]])

In [59]:
arr6[1][0][4]

45

In [83]:
import random
ht = [random.uniform(60, 80) for _ in range(50)]
print(ht)
new_ht = list(filter(lambda height: height > 70, ht))

print("Player_heights_greater than 70 in:")
print(new_ht)

[67.07179489595738, 74.04715553557887, 69.81539977125064, 70.23845784030563, 76.4288663343049, 65.98334197850194, 71.97615593910113, 70.2691750060771, 77.84767830932981, 64.19382966480609, 65.84513299843675, 79.88715639646296, 67.72345694505286, 65.57183449242154, 69.28778026674505, 75.73205695020312, 67.00568199691011, 78.3297932064028, 61.97476681800446, 61.71338356868419, 66.23281768080325, 65.07609549862295, 69.0947776423956, 71.5810290944998, 76.07294229661181, 73.88663632782642, 67.09064163323839, 69.84083590467729, 77.32889100745203, 75.68484264948238, 74.95357523674227, 63.6574205513465, 65.19521815688623, 73.45141986479535, 77.94182853969565, 61.553565831227566, 72.76733143037171, 70.56223623325762, 63.152318313929385, 74.01737690051233, 77.07651486038363, 79.39068363157163, 64.39126862019924, 76.6479984857057, 67.50814707786397, 76.283991162609, 73.49987546552488, 66.54479519520117, 63.861274998300516, 72.05872231932278]
Player_heights_greater than 70 in:
[74.04715553557887, 

In [82]:
random.randrange(60,80)

63

In [1]:
import numpy as np

In [5]:
lst=[i for i in range(10)]
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
arr=np.arange(10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr2=np.arange(60,70)
arr2

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [8]:
arr3=np.arange(50,70,2)
arr3

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68])

    Reshape
        10 = 1,2,5,10
            2,5
            5,2
            10,1
            1,10

In [10]:
arr2.ndim,arr2.size,arr2.shape

(1, 10, (10,))

In [12]:
arr4=arr2.reshape(2,5)
arr4,arr4.ndim,arr4.size,arr4.shape

(array([[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]),
 2,
 10,
 (2, 5))

In [13]:
arr5=arr2.reshape(5,2)
arr5,arr5.ndim,arr5.size,arr5.shape

(array([[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69]]),
 2,
 10,
 (5, 2))

In [14]:
arr6=arr2.reshape(5,3)
arr6,arr6.ndim,arr6.size,arr6.shape

ValueError: cannot reshape array of size 10 into shape (5,3)

In [16]:
arr7=np.arange(12)
arr7,arr7.ndim,arr7.size,arr7.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), 1, 12, (12,))

    12 = 1,2,3,4,6,12
        12,1
        6,2
        4,3
        2,2,3
        1,6,2
        1,2,2,3


In [18]:
arr8=arr7.reshape(3,2,1,2)
arr8,arr8.ndim,arr8.size,arr8.shape

(array([[[[ 0,  1]],
 
         [[ 2,  3]]],
 
 
        [[[ 4,  5]],
 
         [[ 6,  7]]],
 
 
        [[[ 8,  9]],
 
         [[10, 11]]]]),
 4,
 12,
 (3, 2, 1, 2))

In [19]:
arr9=arr8.flatten()
arr9,arr9.ndim,arr9.size,arr9.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), 1, 12, (12,))

    Stacking

In [20]:
arr1=np.arange(5)
arr2= np.arange(5,10) 
arr1,arr2

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

    Concatenation
        axis 
            0 row
            1 col

In [24]:
arr3=np.concatenate((arr1,arr2))
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1]:
arr4=np.concatenate((arr1,arr2),axis=1)
arr4

NameError: name 'np' is not defined