    Good Strings
    You are given a set 'S' of distinct characters. You are also given an array 'A' of 'N' strings.
    A String in array 'A' is called good if all the characters of the string is present in the set 'S'.
    You have to find how many strings in the array 'A' are good.

    Input Format
    The first line contains the number of test cases.
    For each test case: The first line contains a string denoting the characters of the set 'S'.
    The next line contains 'N', the number of strings in 'A'.
    The next 'N' lines contains a string each, which are the elements of the array 'A'.
    
    Output Format
    For each test case print the count of good strings in a new line.

    Example 1
    Input:

    1
    abc
    4
    ab
    abd
    cacb
    cabef
    Output:

    2

In [13]:
no_of_test_cases=int(input('Enter the No of Test Cases'))
set_s=set(input('Enter the characters of the Set'))

In [14]:
set_s

{'a', 'b', 'c'}

In [15]:
no_of_ele=int(input('Enter No Of Strings'))
str_lst=[]
for i in range(no_of_ele):
    str_lst.append(input())

['ab', 'abc', 'cabc', 'ckjhdl', 'aaaaacccd', 'ghsakdha']

In [16]:
no_of_good_string=0
for i in str_lst:
    is_good=True
    for char in i:
        if char not in set_s:
            is_good=False
            break
    if is_good:
       no_of_good_string+=1 
no_of_good_string  

3

In [18]:
for test_case in range(int(input())):
    set_s=set(input())
    no_of_ele=int(input())
    str_lst=[]
    for i in range(no_of_ele):
        str_lst.append(input())
    no_of_good_string=0
    for i in str_lst:
        is_good=True
        for char in i:
            if char not in set_s:
                is_good=False
                break
        if is_good:
            no_of_good_string+=1 
    print(no_of_good_string)

In [20]:
for test_case in range(int(input())):
    set_s=set(input())
    no_of_good_string=0
    for i in [input() for i in range(int(input()))]:
        is_good=True
        for char in i:
            if char not in set_s:
                is_good=False
                break
        if is_good:
            no_of_good_string+=1 
    print(no_of_good_string)

2


    You are a data scientist analyzing climate data for a research project. You have a dataset of average monthly temperatures (in degrees Celsius) for a city over the past 10 years. This dataset is represented as a 2D NumPy array, where each row corresponds to a year (from oldest to newest), and each column corresponds to a month (January to December).

In [21]:
import numpy as np
import random as rd

In [22]:
np_temp=np.array([rd.randint(4,36) for i in range(120)])
np_temp

array([18, 24, 26, 13, 22, 10, 15, 28, 27, 25, 12, 22,  8, 29,  5, 34, 33,
       20, 29, 21, 24, 13, 34,  5, 33,  4, 13,  4,  4, 14, 35, 24, 17,  9,
       30,  4, 23, 29, 17,  9, 13, 15, 32,  7,  9, 24, 31, 30, 27, 18, 24,
       19, 12,  8, 26, 10,  8,  7, 25,  6, 16, 26, 32,  8, 35, 17, 27, 12,
       17, 25, 20, 32,  7, 33, 21,  7,  9, 27, 18, 14, 29, 32, 26, 17, 15,
        5, 28,  4, 24, 31,  7,  7,  9, 26, 23, 16,  5,  7, 34,  8, 34, 20,
       28, 17, 20, 34, 20, 11, 33, 20, 36, 25,  4, 21, 22, 25, 36,  6, 18,
       12])

In [24]:
np_temp.size

120

In [25]:
np_temp_2d=np_temp.reshape((10,12))
np_temp_2d

array([[18, 24, 26, 13, 22, 10, 15, 28, 27, 25, 12, 22],
       [ 8, 29,  5, 34, 33, 20, 29, 21, 24, 13, 34,  5],
       [33,  4, 13,  4,  4, 14, 35, 24, 17,  9, 30,  4],
       [23, 29, 17,  9, 13, 15, 32,  7,  9, 24, 31, 30],
       [27, 18, 24, 19, 12,  8, 26, 10,  8,  7, 25,  6],
       [16, 26, 32,  8, 35, 17, 27, 12, 17, 25, 20, 32],
       [ 7, 33, 21,  7,  9, 27, 18, 14, 29, 32, 26, 17],
       [15,  5, 28,  4, 24, 31,  7,  7,  9, 26, 23, 16],
       [ 5,  7, 34,  8, 34, 20, 28, 17, 20, 34, 20, 11],
       [33, 20, 36, 25,  4, 21, 22, 25, 36,  6, 18, 12]])

    Calculate the average temperature for each month across all years. This will give you a 1D array of 12 elements.

In [41]:
np.average(np_temp_2d[:,0]),np.average(np_temp_2d[:,1]),np.average(np_temp_2d[:,2])

(18.5, 19.5, 23.6)

In [40]:
for i in range(12):
    print(np.average(np_temp_2d[:,i]))
    

18.5
19.5
23.6
13.1
19.0
18.3
23.9
16.5
19.6
20.1
23.9
15.5


In [34]:
np_temp_2d.shape

(10, 12)

In [39]:
[np.average(np_temp_2d[:,i]) for i in range(np_temp_2d.shape[1])]

[18.5, 19.5, 23.6, 13.1, 19.0, 18.3, 23.9, 16.5, 19.6, 20.1, 23.9, 15.5]

In [38]:
np_temp_2d.mean(axis=0)

array([18.5, 19.5, 23.6, 13.1, 19. , 18.3, 23.9, 16.5, 19.6, 20.1, 23.9,
       15.5])

In [42]:
np_temp_2d.mean(axis=1)

array([20.16666667, 21.25      , 15.91666667, 19.91666667, 15.83333333,
       22.25      , 20.        , 16.25      , 19.83333333, 21.5       ])

In [43]:
np_temp_2d.mean()

19.291666666666668

In [45]:
np_temp_2d.min(axis=0)

array([ 5,  4,  5,  4,  4,  8,  7,  7,  8,  6, 12,  4])

In [46]:
np_temp_2d.min(axis=1)

array([10,  5,  4,  7,  6,  8,  7,  4,  5,  4])

    For each year, find the month with the highest temperature and the month with the lowest temperature. Report the difference (fluctuation) in temperature for each year.

In [47]:
np_temp_2d.max(axis=1)

array([28, 34, 35, 32, 27, 35, 33, 31, 34, 36])

In [48]:
np_temp_2d.min(axis=1)

array([10,  5,  4,  7,  6,  8,  7,  4,  5,  4])

In [49]:
np_temp_2d.max(axis=1)-np_temp_2d.min(axis=1)

array([18, 29, 31, 25, 21, 27, 26, 27, 29, 32])