In [ ]:
import numpy as np
import random as rd

In [ ]:
arr=np.array([rd.randint(10,50) for i in range(20)])
arr

In [ ]:
arr.size

In [ ]:
arr.ndim

In [ ]:
arr.shape

    reshape()

In [ ]:
ar2=arr.reshape((2,2,5))

In [ ]:
ar2.shape

In [ ]:
arr3=np.array([rd.randint(10,50) for i in range(100)])
arr3

In [ ]:
arr3.shape

    2 50
    2 5 10
    2 5 2 5
    4 25
    10 10

In [ ]:
arr3.reshape((2,5,2,5))

    range()
    randrange()
    arange()

In [ ]:
arr_4 = np.arange(10)
arr_4

In [ ]:
arr_5 = np.arange(5,10)
arr_5

In [ ]:
arr_6 = np.arange(5,15,2)
arr_6

In [ ]:
for i in range(5,15,2):
    print(i)

    Write a python script to create 3d array of shape (2,3,5) which will contain even nos

In [ ]:
arr_7=np.arange(0,60,2)
arr_7

In [ ]:
arr_7= arr_7.reshape((2,3,5))
arr_7

In [ ]:
np.arange(0,60,2).reshape((2,3,5))

    Write a python script to get a 1d array from 3d array of even nos

In [ ]:
arr_7.size

In [ ]:
arr_7.reshape((30))

    flatten() => use to convert nd array  into 1d array

In [ ]:
arr_7.flatten()

In [ ]:
arr_1 = np.array([1, 2, 3,4,5,9])
arr_2 = np.array([6,7,8,9,10,20])
arr_1,arr_2

In [ ]:
ar_h = np.hstack((arr_1, arr_2))
ar_h

In [ ]:
np.vstack((arr_1, arr_2))

In [ ]:
arr_1 = np.array([1, 2, 3,4,5,9])
arr_2 = np.array([6,7,8,9,10,20])
arr_1,arr_2

In [ ]:
ar_h = np.hstack((arr_1, arr_2,arr_1))
ar_h

In [ ]:
np.vstack((arr_1, arr_2,arr_1, arr_2,arr_1))

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

In [ ]:
arr = np.concatenate((arr1, arr2),axis=0)
print(arr)

In [ ]:
arr1=np.arange(24).reshape((2,3,4))
arr1

In [ ]:
arr2=np.arange(24,48).reshape((2,3,4))
arr2

In [ ]:
np.concatenate((arr1, arr2),axis=0)

In [ ]:
np.concatenate((arr1, arr2),axis=1)

    sort()

In [ ]:
arr8=np.array([rd.randint(10,50) for i in range(20)]).reshape((2,2,5))
arr8

In [ ]:
np.sort(arr8)

In [ ]:
np.sort(arr8,axis=1)

In [ ]:
np.sort(arr8)

    To check order parameter on thursday

In [ ]:
arr10=np.arange(25)
arr10

In [ ]:
newarr = np.array_split(arr10, 3)
newarr

In [ ]:
arr11=np.arange(25).reshape((5,5))
arr11

In [ ]:
np.split(arr11,5)

In [ ]:
arr12=np.arange(36).reshape((3,3,4))
arr12

In [ ]:
np.split(arr12,3)

    Mathematical Operations
        Arithmatic
            +
            -
            *
            /
            %

In [ ]:
arr1=np.arange(10)
arr2=np.arange(10,20)

In [ ]:
arr1,arr2

In [ ]:
arr1+arr2

In [ ]:
np.add(arr1,arr2)

In [ ]:
arr1-arr2

In [ ]:
np.subtract(arr1,arr2)

In [ ]:
arr1*arr2

In [ ]:
np.multiply(arr1,arr2)

In [ ]:
arr1/arr2

In [ ]:
np.divide(arr1,arr2)

In [ ]:
arr1//arr2

In [ ]:
np.floor_divide(arr1,arr2)

In [ ]:
arr1%arr2

In [ ]:
np.mod(arr1,arr2)

In [ ]:
arr1**arr2

In [ ]:
np.power(arr1,arr2)

In [ ]:
np.sin(0)

In [ ]:
np.cos(0)

In [117]:
np.log10(10)

1.0

In [ ]:
dir(np)

In [118]:
np.sin(np.deg2rad(90)) 

1.0

In [119]:
print(np.absolute(np.array([1,2,-1,-2])))

[1 2 1 2]


In [120]:
np_heights_in = np.array([74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 74, 69, 71, 74, 73, 73, 76, 74, 74, 70, 72, 77, 74, 70, 73, 75, 76, 76, 78, 74, 74, 76, 77, 81, 78, 75, 77, 75, 76, 74, 72, 72, 75, 73, 73, 73, 70, 70, 70, 76, 68, 71, 72, 75, 75, 75, 75, 68, 74, 78, 71, 73, 76, 74, 74, 79, 75, 73, 76, 74, 74, 73, 72, 74, 73, 74, 72, 73, 69, 72, 73, 75, 75, 73, 72, 72, 76, 74, 72, 77, 74, 77, 75, 76, 80, 74, 74, 75, 78, 73, 73, 74, 75, 76, 71, 73, 74, 76, 76, 74, 73, 74, 70, 72, 73, 73, 73, 73, 71, 74, 74, 72, 74, 71, 74, 73, 75, 75, 79, 73, 75, 76, 74, 76, 78, 74, 76, 72, 74, 76, 74, 75, 78, 75, 72, 74, 72, 74, 70, 71, 70, 75, 71, 71, 73, 72, 71, 73, 72, 75, 74, 74, 75, 73, 77, 73, 76, 75, 74, 76, 75, 73, 71, 76, 75, 72, 71, 77, 73, 74, 71, 72, 74, 75, 73, 72, 75, 75, 74, 72, 74, 71, 70, 74, 77, 77, 75, 75, 78, 75, 76, 73, 75, 75, 79, 77, 76, 71, 75, 74, 69, 71, 76, 72, 72, 70, 72, 73, 71, 72, 71, 73, 72, 73, 74, 74, 72, 75, 74, 74, 77, 75, 73, 72, 71, 74, 77, 75, 75, 75, 78, 78, 74, 76, 78, 76, 70, 72, 80, 74, 74, 71, 70, 72, 71, 74, 71, 72, 71, 74, 69, 76, 75, 75, 76, 73, 76, 73, 77, 73, 72, 72, 77, 77, 71, 74, 74, 73, 78, 75, 73, 70, 74, 72, 73, 73, 75, 75, 74, 76, 73, 74, 75, 75, 72, 73, 73, 72, 74, 78, 76, 73, 74, 75, 70, 75, 71, 72, 78, 75, 73, 73, 71, 75, 77, 72, 69, 73, 74, 72, 70, 75, 70, 72, 72, 74, 73, 74, 76, 75, 80, 72, 75, 73, 74, 74, 73, 75, 75, 71, 73, 75, 74, 74, 72, 74, 74, 74, 73, 76, 75, 72, 73, 73, 73, 72, 72, 72, 72, 71, 75, 75, 74, 73, 75, 79, 74, 76, 73, 74, 74, 72, 74, 74, 75, 78, 74, 74, 74, 77, 70, 73, 74, 73, 71, 75, 71, 72, 77, 74, 70, 77, 73, 72, 76, 71, 76, 78, 75, 73, 78, 74, 79, 75, 76, 72, 75, 75, 70, 72, 70, 74, 71, 76, 73, 76, 71, 69, 72, 72, 69, 73, 69, 73, 74, 74, 72, 71, 72, 72, 76, 76, 76, 74, 76, 75, 71, 72, 71, 73, 75, 76, 75, 71, 75, 74, 72, 73, 73, 73, 73, 76, 72, 76, 73, 73, 73, 75, 75, 77, 73, 72, 75, 70, 74, 72, 80, 71, 71, 74, 74, 73, 75, 76, 73, 77, 72, 73, 77, 76, 71, 75, 73, 74, 77, 71, 72, 73, 69, 73, 70, 74, 76, 73, 73, 75, 73, 79, 74, 73, 74, 77, 75, 74, 73, 77, 73, 77, 74, 74, 73, 77, 74, 77, 75, 77, 75, 71, 74, 70, 79, 72, 72, 70, 74, 74, 72, 73, 72, 74, 74, 76, 82, 74, 74, 70, 73, 73, 74, 77, 72, 76, 73, 73, 72, 74, 74, 71, 72, 75, 74, 74, 77, 70, 71, 73, 76, 71, 75, 74, 72, 76, 79, 76, 73, 76, 78, 75, 76, 72, 72, 73, 73, 75, 71, 76, 70, 75, 74, 75, 73, 71, 71, 72, 73, 73, 72, 69, 73, 78, 71, 73, 75, 76, 70, 74, 77, 75, 79, 72, 77, 73, 75, 75, 75, 73, 73, 76, 77, 75, 70, 71, 71, 75, 74, 69, 70, 75, 72, 75, 73, 72, 72, 72, 76, 75, 74, 69, 73, 72, 72, 75, 77, 76, 80, 77, 76, 79, 71, 75, 73, 76, 77, 73, 76, 70, 75, 73, 75, 70, 69, 71, 72, 72, 73, 70, 70, 73, 76, 75, 72, 73, 79, 71, 72, 74, 74, 74, 72, 76, 76, 72, 72, 71, 72, 72, 70, 77, 74, 72, 76, 71, 76, 71, 73, 70, 73, 73, 72, 71, 71, 71, 72, 72, 74, 74, 74, 71, 72, 75, 72, 71, 72, 72, 72, 72, 74, 74, 77, 75, 73, 75, 73, 76, 72, 77, 75, 72, 71, 71, 75, 72, 73, 73, 71, 70, 75, 71, 76, 73, 68, 71, 72, 74, 77, 72, 76, 78, 81, 72, 73, 76, 72, 72, 74, 76, 73, 76, 75, 70, 71, 74, 72, 73, 76, 76, 73, 71, 68, 71, 71, 74, 77, 69, 72, 76, 75, 76, 75, 76, 72, 74, 76, 74, 72, 75, 78, 77, 70, 72, 79, 74, 71, 68, 77, 75, 71, 72, 70, 72, 72, 73, 72, 74, 72, 72, 75, 72, 73, 74, 72, 78, 75, 72, 74, 75, 75, 76, 74, 74, 73, 74, 71, 74, 75, 76, 74, 76, 76, 73, 75, 75, 74, 68, 72, 75, 71, 70, 72, 73, 72, 75, 74, 70, 76, 71, 82, 72, 73, 74, 71, 75, 77, 72, 74, 72, 73, 78, 77, 73, 73, 73, 73, 73, 76, 75, 70, 73, 72, 73, 75, 74, 73, 73, 76, 73, 75, 70, 77, 72, 77, 74, 75, 75, 75, 75, 72, 74, 71, 76, 71, 75, 76, 83, 75, 74, 76, 72, 72, 75, 75, 72, 77, 73, 72, 70, 74, 72, 74, 72, 71, 70, 71, 76, 74, 76, 74, 74, 74, 75, 75, 71, 71, 74, 77, 71, 74, 75, 77, 76, 74, 76, 72, 71, 72, 75, 73, 68, 72, 69, 73, 73, 75, 70, 70, 74, 75, 74, 74, 73, 74, 75, 77, 73, 74, 76, 74, 75, 73, 76, 78, 75, 73, 77, 74, 72, 74, 72, 71, 73, 75, 73, 67, 67, 76, 74, 73, 70, 75, 70, 72, 77, 79, 78, 74, 75, 75, 78, 76, 75, 69, 75, 72, 75, 73, 74, 75, 75, 73])


In [121]:
np_weights_lb = np.array([180, 215, 210, 210, 188, 176, 209, 200, 231, 180, 188, 180, 185, 160, 180, 185, 189, 185, 219, 230, 205, 230, 195, 180, 192, 225, 203, 195, 182, 188, 200, 180, 200, 200, 245, 240, 215, 185, 175, 199, 200, 215, 200, 205, 206, 186, 188, 220, 210, 195, 200, 200, 212, 224, 210, 205, 220, 195, 200, 260, 228, 270, 200, 210, 190, 220, 180, 205, 210, 220, 211, 200, 180, 190, 170, 230, 155, 185, 185, 200, 225, 225, 220, 160, 205, 235, 250, 210, 190, 160, 200, 205, 222, 195, 205, 220, 220, 170, 185, 195, 220, 230, 180, 220, 180, 180, 170, 210, 215, 200, 213, 180, 192, 235, 185, 235, 210, 222, 210, 230, 220, 180, 190, 200, 210, 194, 180, 190, 240, 200, 198, 200, 195, 210, 220, 190, 210, 225, 180, 185, 170, 185, 185, 180, 178, 175, 200, 204, 211, 190, 210, 190, 190, 185, 290, 175, 185, 200, 220, 170, 220, 190, 220, 205, 200, 250, 225, 215, 210, 215, 195, 200, 194, 220, 180, 180, 170, 195, 180, 170, 206, 205, 200, 225, 201, 225, 233, 180, 225, 180, 220, 180, 237, 215, 190, 235, 190, 180, 165, 195, 200, 190, 190, 185, 185, 205, 190, 205, 206, 220, 208, 170, 195, 210, 190, 211, 230, 170, 185, 185, 241, 225, 210, 175, 230, 200, 215, 198, 226, 278, 215, 230, 240, 184, 219, 170, 218, 190, 225, 220, 176, 190, 197, 204, 167, 180, 195, 220, 215, 185, 190, 205, 205, 200, 210, 215, 200, 205, 211, 190, 208, 200, 210, 232, 230, 210, 220, 210, 202, 212, 225, 170, 190, 200, 237, 220, 170, 193, 190, 150, 220, 200, 190, 185, 185, 200, 172, 220, 225, 190, 195, 219, 190, 197, 200, 195, 210, 177, 220, 235, 180, 195, 195, 190, 230, 190, 200, 190, 190, 200, 200, 184, 200, 180, 219, 187, 200, 220, 205, 190, 170, 160, 215, 175, 205, 200, 214, 200, 190, 180, 205, 220, 190, 215, 235, 191, 200, 181, 200, 210, 240, 185, 165, 190, 185, 175, 155, 210, 170, 175, 220, 210, 205, 200, 205, 195, 240, 150, 200, 215, 202, 200, 190, 205, 190, 160, 215, 185, 200, 190, 210, 185, 220, 190, 202, 205, 220, 175, 160, 190, 200, 229, 206, 220, 180, 195, 175, 188, 230, 190, 200, 190, 219, 235, 180, 180, 180, 200, 234, 185, 220, 223, 200, 210, 200, 210, 190, 177, 227, 180, 195, 199, 175, 185, 240, 210, 180, 194, 225, 180, 205, 193, 230, 230, 220, 200, 249, 190, 208, 245, 250, 160, 192, 220, 170, 197, 155, 190, 200, 220, 210, 228, 190, 160, 184, 180, 180, 200, 176, 160, 222, 211, 195, 200, 175, 206, 240, 185, 260, 185, 221, 205, 200, 170, 201, 205, 185, 205, 245, 220, 210, 220, 185, 175, 170, 180, 200, 210, 175, 220, 206, 180, 210, 195, 200, 200, 164, 180, 220, 195, 205, 170, 240, 210, 195, 200, 205, 192, 190, 170, 240, 200, 205, 175, 250, 220, 224, 210, 195, 180, 245, 175, 180, 215, 175, 180, 195, 230, 230, 205, 215, 195, 180, 205, 180, 190, 180, 190, 190, 220, 210, 255, 190, 230, 200, 205, 210, 225, 215, 220, 205, 200, 220, 197, 225, 187, 245, 185, 185, 175, 200, 180, 188, 225, 200, 210, 245, 213, 231, 165, 228, 210, 250, 191, 190, 200, 215, 254, 232, 180, 215, 220, 180, 200, 170, 195, 210, 200, 220, 165, 180, 200, 200, 170, 224, 220, 180, 198, 240, 239, 185, 210, 220, 200, 195, 220, 230, 170, 220, 230, 165, 205, 192, 210, 205, 200, 210, 185, 195, 202, 205, 195, 180, 200, 185, 240, 185, 220, 205, 205, 180, 201, 190, 208, 240, 180, 230, 195, 215, 190, 195, 215, 215, 220, 220, 230, 195, 190, 195, 209, 204, 170, 185, 205, 175, 210, 190, 180, 180, 160, 235, 200, 210, 180, 190, 197, 203, 205, 170, 200, 250, 200, 220, 200, 190, 170, 190, 220, 215, 206, 215, 185, 235, 188, 230, 195, 168, 190, 160, 200, 200, 189, 180, 190, 200, 220, 187, 240, 190, 180, 185, 210, 220, 219, 190, 193, 175, 180, 215, 210, 200, 190, 185, 220, 170, 195, 205, 195, 210, 190, 190, 180, 220, 190, 186, 185, 190, 180, 190, 170, 210, 240, 220, 180, 210, 210, 195, 160, 180, 205, 200, 185, 245, 190, 210, 200, 200, 222, 215, 240, 170, 220, 156, 190, 202, 221, 200, 190, 210, 190, 200, 165, 190, 185, 230, 208, 209, 175, 180, 200, 205, 200, 250, 210, 230, 244, 202, 240, 200, 215, 177, 210, 170, 215, 217, 198, 200, 220, 170, 200, 230, 231, 183, 192, 167, 190, 180, 180, 215, 160, 205, 223, 175, 170, 190, 240, 175, 230, 223, 196, 167, 195, 190, 250, 190, 190, 190, 170, 160, 150, 225, 220, 209, 210, 176, 260, 195, 190, 184, 180, 195, 195, 219, 225, 212, 202, 185, 200, 209, 200, 195, 228, 210, 190, 212, 190, 218, 220, 190, 235, 210, 200, 188, 210, 235, 188, 215, 216, 220, 180, 185, 200, 210, 220, 185, 231, 210, 195, 200, 205, 200, 190, 250, 185, 180, 170, 180, 208, 235, 215, 244, 220, 185, 230, 190, 200, 180, 190, 196, 180, 230, 224, 160, 178, 205, 185, 210, 180, 190, 200, 257, 190, 220, 165, 205, 200, 208, 185, 215, 170, 235, 210, 170, 180, 170, 190, 150, 230, 203, 260, 246, 186, 210, 198, 210, 215, 180, 200, 245, 200, 192, 192, 200, 192, 205, 190, 186, 170, 197, 219, 200, 220, 207, 225, 207, 212, 225, 170, 190, 210, 230, 210, 200, 238, 234, 222, 200, 190, 170, 220, 223, 210, 215, 196, 175, 175, 189, 205, 210, 180, 180, 197, 220, 228, 190, 204, 165, 216, 220, 208, 210, 215, 195, 200, 215, 229, 240, 207, 205, 208, 185, 190, 170, 208, 225, 190, 225, 185, 180, 165, 240, 220, 212, 163, 215, 175, 205, 210, 205, 208, 215, 180, 200, 230, 211, 230, 190, 220, 180, 205, 190, 180, 205, 190, 195])

In [122]:
np_height_m=np_heights_in*0.0254
np_height_m

array([1.8796, 1.8796, 1.8288, ..., 1.905 , 1.905 , 1.8542])

In [123]:
np_weight_kg=np_weights_lb*0.453592
np_weight_kg

array([81.64656, 97.52228, 95.25432, ..., 92.98636, 86.18248, 88.45044])

In [126]:
np_bmi=(np_weight_kg/np_height_m**2)
np_bmi.round(2)

array([23.11, 27.6 , 28.48, ..., 25.62, 23.75, 25.73])

In [133]:
round((np_bmi[(np_bmi>18) & (np_bmi <25)].size/np_bmi.size)*100,2)

33.0

    Descriptive
        Measure of central tendency
        Measure of spread
        Measure of Symmetry
        Types of Charts
        Outliers/ Correlation

In [134]:
arr=np.array([rd.randrange(50,90) for i in range(50)])
arr

array([79, 66, 71, 85, 57, 86, 88, 81, 74, 73, 65, 86, 78, 81, 73, 89, 77,
       79, 52, 78, 51, 50, 69, 83, 65, 85, 58, 78, 66, 85, 81, 76, 78, 63,
       76, 65, 85, 70, 84, 80, 77, 68, 58, 62, 53, 85, 71, 82, 82, 83])

In [135]:
arr.size

50

In [136]:
arr.max()

89

In [137]:
np.max(arr)

89

In [138]:
np.min(arr)

50

In [139]:
np.mean(arr)

73.74

In [140]:
np.median(arr)

77.0

In [141]:
np.average(arr)

73.74

In [142]:
np.std(arr)

10.571300771428273

In [143]:
np.var(arr)

111.7524

In [144]:
np.cov(arr)

array(114.03306122)

In [145]:
np.corrcoef(arr)

1.0

In [146]:
import statistics as st

In [148]:
st.mode(arr)

85

In [149]:
arr

array([79, 66, 71, 85, 57, 86, 88, 81, 74, 73, 65, 86, 78, 81, 73, 89, 77,
       79, 52, 78, 51, 50, 69, 83, 65, 85, 58, 78, 66, 85, 81, 76, 78, 63,
       76, 65, 85, 70, 84, 80, 77, 68, 58, 62, 53, 85, 71, 82, 82, 83])

In [150]:
np.sum(arr)

3687

In [151]:
x=np.array([1,2,3,4,70,6])
print(np.add.reduce(x))
print(x.sum())

86
86


In [152]:
np.subtract.reduce(x)

-84

In [153]:
print(np.add.accumulate(x))

[ 1  3  6 10 80 86]


In [154]:
np_qty=np.array([8, 9, 9, 1, 6, 9, 5, 7, 3, 9, 7, 3, 4, 8, 3, 5, 8, 4, 8, 7, 5, 7, 3, 6, 1, 2, 7, 4, 7, 7, 8, 4, 3, 4, 2, 2, 2, 7, 3, 5, 6, 1, 1, 3, 2, 1, 1, 7, 7, 1, 4, 4, 5, 6, 1, 2, 7, 4, 5, 8, 1, 4, 8, 6, 2, 4, 3, 7, 3, 6, 2, 3, 3, 3, 2, 4, 6, 8, 9, 3, 9, 3, 1, 8, 6, 6, 3, 3, 9, 4, 6, 4, 9, 6, 7, 1, 2, 8, 7, 8, 1, 4])

In [155]:
np_price = np.array([195, 225, 150, 150, 90, 60, 75, 255, 270, 225, 135, 195, 30, 15, 210, 105, 15, 30, 180, 60, 165, 60, 45, 225, 180, 90, 30, 210, 150, 15, 270, 60, 210, 180, 60, 225, 150, 150, 120, 195, 75, 240, 60, 45, 30, 180, 240, 285, 135, 165, 180, 240, 60, 105, 165, 240, 120, 45, 120, 165, 285, 225, 90, 105, 225, 45, 45, 45, 75, 180, 90, 240, 30, 30, 60, 135, 180, 15, 255, 180, 270, 135, 105, 135, 210, 180, 135, 195, 225, 75, 225, 15, 240, 60, 15, 180, 255, 90, 15, 150, 230, 150])

In [156]:
np_sale=np_qty*np_price
np_sale

array([1560, 2025, 1350,  150,  540,  540,  375, 1785,  810, 2025,  945,
        585,  120,  120,  630,  525,  120,  120, 1440,  420,  825,  420,
        135, 1350,  180,  180,  210,  840, 1050,  105, 2160,  240,  630,
        720,  120,  450,  300, 1050,  360,  975,  450,  240,   60,  135,
         60,  180,  240, 1995,  945,  165,  720,  960,  300,  630,  165,
        480,  840,  180,  600, 1320,  285,  900,  720,  630,  450,  180,
        135,  315,  225, 1080,  180,  720,   90,   90,  120,  540, 1080,
        120, 2295,  540, 2430,  405,  105, 1080, 1260, 1080,  405,  585,
       2025,  300, 1350,   60, 2160,  360,  105,  180,  510,  720,  105,
       1200,  230,  600])

In [157]:
np_sale.size

102

In [158]:
np.sum(np_qty)

490

In [159]:
np.mean(np_price)

139.01960784313727

In [160]:
np.max(np_price)

285

In [161]:
np.sum(np_sale)

67100

In [162]:
np_qty[19]

7

In [163]:
np_qty[49]

1

In [164]:
True if np_qty[19]> np_qty[49] else False

True

In [165]:
np.average(np_price)

139.01960784313727

In [166]:
np_price[np_price>np.average(np_price)].size

52

    7x+5y-3z=16
    3x-5y+2z=-8
    5x+3y-7z=0

In [167]:
a = np.array([ [7,5,-3],[3,-5,2],[5,3,-7] ])
a

array([[ 7,  5, -3],
       [ 3, -5,  2],
       [ 5,  3, -7]])

In [168]:
b = np.array([16,-8,0])
b

array([16, -8,  0])

In [169]:
np.linalg.solve(a,b)

array([1., 3., 2.])

In [170]:
a = np.array([ [7,5,-3],[3,-5,2],[5,3,-7] ])
print(a)

np.linalg.inv(a)

[[ 7  5 -3]
 [ 3 -5  2]
 [ 5  3 -7]]


array([[ 0.11328125,  0.1015625 , -0.01953125],
       [ 0.12109375, -0.1328125 , -0.08984375],
       [ 0.1328125 ,  0.015625  , -0.1953125 ]])

In [171]:
A = np.array([[1, 1],
              [0, 1]])

B = np.array([[2, 0],
              [3, 4]])

In [172]:
A@B

array([[5, 4],
       [3, 4]])

In [173]:
np.dot(A,B)

array([[5, 4],
       [3, 4]])

In [174]:
np.cross(A,B)

array([-2, -3])

The following ways are commonly used:

* np.arange(): Create array with increments of a fixed step size
* np.ones(): Create array of 1s
* np.zeros(): Create array of 0s
* np.linspace(): Create array of fixed length
* np.full(): Create a constant array of any number ‘n’
* np.tile(): Create a new array by repeating an existing array for a particular number of times
* np.eye(): Create an identity matrix of any dimension
* np.random.random(): Create array of random numbers between 0 and 1
* np.random.randint(): Create a random array of integers within a particular range