In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

    range(5)
        0 1 2 3 4

In [2]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

    create a array of even no less than 10

In [3]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [5]:
np.zeros(5,dtype='int')

array([0, 0, 0, 0, 0])

   Create a array of 4,2,3 dim which will have only zeros as element

In [7]:
np.zeros(24,dtype='int').reshape((4,2,3))

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [9]:
np.ones(5,dtype='int')

array([1, 1, 1, 1, 1])

In [10]:
np.linspace(5,15,5)

array([ 5. ,  7.5, 10. , 12.5, 15. ])

In [ ]:
min = 5
max = 15

In [12]:
np.linspace(10,20,10,retstep=True)

(array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
        15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ]),
 1.1111111111111112)

In [13]:
np.full(5,'Si')

array(['Si', 'Si', 'Si', 'Si', 'Si'], dtype='<U2')

In [16]:
np.full(5,0.0)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.eye(3,dtype='int')*5

array([[5, 0, 0],
       [0, 5, 0],
       [0, 0, 5]])

In [22]:
import random as rd

In [23]:
np.array([rd.randint(10,50) for i in range(10)])

array([48, 50, 46, 45, 35, 15, 44, 14, 37, 36])

In [34]:
np.random.random((3,4,5))

array([[[0.59428033, 0.87181448, 0.94988339, 0.9526397 , 0.79837102],
        [0.05126731, 0.22682912, 0.61108034, 0.09464902, 0.93191513],
        [0.55036483, 0.59015846, 0.26705621, 0.64281584, 0.59716231],
        [0.52700336, 0.88786495, 0.7299509 , 0.5026376 , 0.14510791]],

       [[0.28725455, 0.2654707 , 0.07656188, 0.84917653, 0.49872002],
        [0.21629059, 0.90768152, 0.35902574, 0.77237431, 0.56042074],
        [0.75199129, 0.39898212, 0.38827923, 0.38450219, 0.27907136],
        [0.8010568 , 0.3558972 , 0.19026823, 0.64194868, 0.14691599]],

       [[0.38774734, 0.8271988 , 0.8080924 , 0.89679473, 0.35680379],
        [0.76260496, 0.02014195, 0.54139648, 0.4329741 , 0.48134335],
        [0.92698428, 0.10605663, 0.74214164, 0.07420691, 0.57248964],
        [0.24205213, 0.17342537, 0.68338681, 0.12904386, 0.18313058]]])

In [39]:
np.random.randint(20,30,(2,2,2,2))

array([[[[29, 22],
         [24, 22]],

        [[23, 29],
         [27, 23]]],


       [[[21, 21],
         [24, 25]],

        [[21, 22],
         [23, 27]]]])

In [40]:
arr2=np.random.randint(80,90,(2,3))
arr2

array([[80, 81, 80],
       [86, 85, 83]])

In [42]:
np.tile(arr2,(2,2))

array([[80, 81, 80, 80, 81, 80],
       [86, 85, 83, 86, 85, 83],
       [80, 81, 80, 80, 81, 80],
       [86, 85, 83, 86, 85, 83]])

In [49]:
import pandas as pd
import numpy as np

In [48]:
! pip install pandas

In [50]:
pd.Series(np.random.randint(10,50,10))

0    33
1    34
2    42
3    44
4    14
5    49
6    16
7    13
8    19
9    20
dtype: int32

In [53]:
pd.Series(['Sulochna','Aditi','Aditya','Ajit'],name="Student Name")

0    Sulochna
1       Aditi
2      Aditya
3        Ajit
Name: Student Name, dtype: object

In [58]:
marks=[7.25,8.3,8.5,8.6]

In [64]:
se_marks=pd.Series(marks,name='Student_name')
se_marks

0    7.25
1    8.30
2    8.50
3    8.60
Name: Student_name, dtype: float64

In [65]:
se_marks[2]

8.5

In [69]:
se_n_marks=pd.Series(marks,index=['Sulochna','Aditi','Aditya','Ajit'],name='Student_name')
se_n_marks

Sulochna    7.25
Aditi       8.30
Aditya      8.50
Ajit        8.60
Name: Student_name, dtype: float64

<img src='../data/datatype.png'>

In [70]:
se_n_marks.ndim

1

In [71]:
se_n_marks.size

4

In [72]:
se_n_marks.shape

(4,)

In [73]:
se_n_marks.index

Index(['Sulochna', 'Aditi', 'Aditya', 'Ajit'], dtype='object')

In [74]:
se_n_marks.name

'Student_name'

In [67]:
se_n_marks['Ajit']

8.6

In [54]:
population_dict = {
    'California':38956785,
    'Texas':26441568,
    'New York':19555647,
    'Florida':12364569,
    'Illinois':12882135
}

population_dict

{'California': 38956785,
 'Texas': 26441568,
 'New York': 19555647,
 'Florida': 12364569,
 'Illinois': 12882135}

In [55]:
pd.Series(population_dict)

California    38956785
Texas         26441568
New York      19555647
Florida       12364569
Illinois      12882135
dtype: int64

In [56]:
pd.Series(population_dict.values())

0    38956785
1    26441568
2    19555647
3    12364569
4    12882135
dtype: int64

In [57]:
pd.Series(population_dict.keys())

0    California
1         Texas
2      New York
3       Florida
4      Illinois
dtype: object

1. **Stock Prices Analysis**:
   - Problem: You have a Series `stock_prices` representing the closing stock prices of a company over five consecutive days: `{'Monday': 142.90, 'Tuesday': 144.55, 'Wednesday': 145.30, 'Thursday': 145.85, 'Friday': 146.20}`. Calculate the average closing price for the week. Also, find out on which day the stock price was the highest.

2. **Student Grades Processing**:
   - Problem: A teacher has a Pandas Series `grades` containing the final grades of students in a class: `{'John': 88, 'Emma': 92, 'Ava': 76, 'Mia': 89, 'Oliver': 95}`. The teacher decides to boost each student's grade by 5 points as a year-end bonus. Update the Series to reflect this change. Then, find out which student has the highest grade after the bonus.

3. **Temperature Data Handling**:
   - Problem: A meteorological department stores a week's temperature data in Celsius in a Pandas Series `temperatures`: `[20, 22, 19, 21, 24, 24, 23]`. Convert these temperatures to Fahrenheit using the formula `F = C * 9/5 + 32` and create a new Series `temperatures_fahrenheit`.

4. **Library Book Tracking**:
   - Problem: A small library uses a Pandas Series `books` to track the number of copies of each book title available: `{'To Kill a Mockingbird': 3, '1984': 4, 'The Great Gatsby': 2, 'Pride and Prejudice': 5}`. The library acquires two more copies of 'The Great Gatsby'. Update the Series to reflect this. Then, calculate the total number of books available in the library.

5. **Grocery Store Inventory**:
   - Problem: A grocery store maintains its inventory in a Series `inventory`: `{'Apples': 30, 'Bananas': 45, 'Oranges': 20, 'Grapes': 35}`. During a sale, 10 bananas, 5 oranges, and 15 grapes are sold. Update the Series to reflect the new inventory. Additionally, find out which fruit has the lowest quantity in stock after the sale.



In [75]:
stock_prices=pd.Series({'Monday': 142.90, 'Tuesday': 144.55, 'Wednesday': 145.30, 'Thursday': 145.85, 'Friday': 146.20})
stock_prices

Monday       142.90
Tuesday      144.55
Wednesday    145.30
Thursday     145.85
Friday       146.20
dtype: float64

In [76]:
np.average(stock_prices)

144.95999999999998

In [77]:
np.max(stock_prices)

146.2

In [78]:
grades=pd.Series({'John': 88, 'Emma': 92, 'Ava': 76, 'Mia': 89, 'Oliver': 95})
grades

John      88
Emma      92
Ava       76
Mia       89
Oliver    95
dtype: int64

In [79]:
grades_bonus=grades+5
grades_bonus

John       93
Emma       97
Ava        81
Mia        94
Oliver    100
dtype: int64

In [88]:
grades_bonus.idxmax()

'Oliver'

In [93]:
pd.Series(np.random.randint(10,50,10))

0    10
1    47
2    15
3    41
4    46
5    22
6    23
7    41
8    25
9    29
dtype: int32

In [39]:
ser=pd.Series(np.random.randint(10,50,10),name='qw1',index=['r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7', 'r8', 'r9', 'r10'])
ser

r1     38
r2     27
r3     29
r4     19
r5     48
r6     33
r7     44
r8     19
r9     10
r10    26
Name: qw1, dtype: int32

In [42]:
pd.DataFrame(ser,columns=['qw1'],index=['rq1', 'r2', 'r3', 'r24', 'r5', 'r6', 'r7', 'r8', 'r9', 'r10'])

qw1
rq1   NaN
r2   27.0
r3   29.0
r24   NaN
r5   48.0
r6   33.0
r7   44.0
r8   19.0
r9   10.0
r10  26.0

In [14]:
df=pd.DataFrame(
    pd.Series(np.random.randint(10,50,10)))
df

0
0  42
1  48
2  36
3  15
4  30
5  19
6  48
7  14
8  40
9  38

In [8]:
df.ndim,df.shape,df.size

(2, (2, 10), 20)

In [12]:
df.index

Index(['da1', 'da2'], dtype='object')

In [10]:
df.columns

RangeIndex(start=0, stop=10, step=1)

In [13]:
pd.DataFrame([pd.Series([i for i in range(1,20,2)],name='Odd_numbers'),pd.Series([i for i in range(1,20,2)],name='Odd_numbers')])

0  1  2  3  4   5   6   7   8   9
Odd_numbers  1  3  5  7  9  11  13  15  17  19
Odd_numbers  1  3  5  7  9  11  13  15  17  19

In [34]:
population_dict = {
    'California':38956785,
    'Texas':26441568,
    'New York':19555647,
    'Florida':12364569,
    'Illinois':12882135
}

In [17]:
pop={
    'Ajit':['Excel','Sql']
}
pd.DataFrame(pop)

Ajit
0  Excel
1    Sql

In [22]:
stude_marks={
    'Excel':[512,1],
    'SQL':[12,15]
}

In [23]:
pd.DataFrame(stude_marks)

Excel  SQL
0    512   12
1      1   15

In [4]:
data = {
        'col_1': [3, 2, 1, 0],
        'col_2': ['a', 'b', 'c', 'd']
    }
pd.DataFrame.from_dict(data)


col_1 col_2
0      3     a
1      2     b
2      1     c
3      0     d

In [3]:
import pandas as pd
import numpy as np

In [36]:
pd.DataFrame(pd.Series(population_dict,name='Population'))

Population
California    38956785
Texas         26441568
New York      19555647
Florida       12364569
Illinois      12882135

In [37]:
path='https://raw.githubusercontent.com/ubaid-shah/datasets/main/student_records.csv'
df = pd.read_csv(path)
df

Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90          85.0       Yes
1    John            C        N             85          51.0       Yes
2   David            F        N             10          17.0        No
3  Holmes            B        Y             75          71.0        No
4  Marvin            E        N             20          30.0        No
5   Simon            A        Y             92          79.0       Yes
6  Robert            B        Y             60          59.0        No
7   Trent            C        Y             75          33.0        No
8    Judy          NaN        Y             25           NaN        No
9   Chris            D        U             25          15.0        NO