    Python
        Core 
            print
            constants
            variable
            operator
                arithmatic 
                conditional
                logical 
            data types
                boolean
                int
                float
                string
            data structures
                list
                tuple
                array
                set
                dictionary
            Conditional Statements
                Ifs
            Control statements
                loops
                    while 
                    for
                pass
                break
                continue
            Functions
                built in 
                    string function
                User defined
            local and global variable
            List comprehension
            Exception Handling
            Lambda
            map
            filter
            libraries
                Array
                string
                random          

    Data Collection
        CSV
        SQL
        EXCEL
        XML
    Data Ingestion / Import
        pandas/numpy
    Data Cleaning
        pandas/numpy
    Data Transformation
        pandas/numpy
            join
            union
            grouby
    Data Visulaization
        matplotlib

    homo => same
    hetro => different  

    To install any library
    from Jupyter notebook
        !pip install <name_of_library>
    From Command prompt
        py -m pip install <name_of_library>

    py -m pip install numpy

In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.2'

    Create a numpy array

        np.array(iterable/data_types)

In [17]:
arr7=np.array([])
arr7

array([], dtype=float64)

In [6]:
arr=np.array(1)
arr

array(1)

In [7]:
arr1=np.array('Siraj')
arr1

array('Siraj', dtype='<U5')

In [9]:
arr3=np.array(True)
arr3

array(True)

In [10]:
arr4=np.array(1.2)
arr4

array(1.2)

In [11]:
arr5=np.array([1,2,3])
arr5

array([1, 2, 3])

In [15]:
arr6=np.array(tuple([1,2,3]))
arr6

array([1, 2, 3])

    Slicing / Accessing


In [18]:
arr1

array('Siraj', dtype='<U5')

In [19]:
arr1[0]

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [20]:
arr6

array([1, 2, 3])

In [21]:
arr6[0]

1

In [22]:
arr6[-1]

3

In [23]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [24]:
arr6

array([1, 2, 3])

In [25]:
type(arr6)

numpy.ndarray

In [26]:
arr6

array([1, 2, 3])

In [27]:
len(arr6)

3

In [28]:
arr6.size

3

In [29]:
arr6.ndim

1

In [30]:
arr1

array('Siraj', dtype='<U5')

In [31]:
arr1.ndim

0

In [32]:
arr6.dtype

dtype('int32')

In [33]:
arr8=np.array([True])
arr8

array([ True])

In [34]:
arr8=np.array([True,150])
arr8

array([  1, 150])

In [35]:
arr8=np.array([True,150,198.7])
arr8

array([  1. , 150. , 198.7])

In [36]:
arr8=np.array([True,150,198.7,'Siraj'])
arr8

array(['True', '150', '198.7', 'Siraj'], dtype='<U32')

    What is the difference between numpy and list
    Why we numpy when we already have list
    

In [37]:
lst1=[1,2]
lst2=[2,3]
lst1+lst2

[1, 2, 2, 3]

In [38]:
ar1=np.array(lst1)
ar2=np.array(lst2)
ar1+ar2

array([3, 5])

In [39]:
import random as rd

In [40]:
ar1=np.array([rd.randint(10,99) for i in range(10)])
ar1

array([32, 26, 41, 14, 17, 14, 10, 67, 17, 37])

In [41]:
ar1.size

10

In [42]:
ar1.dtype

dtype('int32')

In [43]:
ar1.ndim

1

In [44]:
ar1.shape

(10,)

In [45]:
ar2=np.array([ar1,ar1])
ar2

array([[32, 26, 41, 14, 17, 14, 10, 67, 17, 37],
       [32, 26, 41, 14, 17, 14, 10, 67, 17, 37]])

In [46]:
ar2.size

20

In [47]:
ar2.dtype

dtype('int32')

In [48]:
ar2.ndim

2

In [49]:
ar2.shape

(2, 10)

In [50]:
ar3=np.array([rd.randint(10,99) for i in range(12)])
ar3

array([91, 66, 12, 36, 54, 37, 92, 16, 63, 75, 94, 33])

In [51]:
ar3.shape

(12,)

    reshape

In [53]:
ar3.reshape((3,4))

array([[91, 66, 12, 36],
       [54, 37, 92, 16],
       [63, 75, 94, 33]])

In [54]:
ar3.reshape((4,3))

array([[91, 66, 12],
       [36, 54, 37],
       [92, 16, 63],
       [75, 94, 33]])

In [55]:
ar3.reshape((2,6))

array([[91, 66, 12, 36, 54, 37],
       [92, 16, 63, 75, 94, 33]])

In [56]:
ar3.reshape((6,2))

array([[91, 66],
       [12, 36],
       [54, 37],
       [92, 16],
       [63, 75],
       [94, 33]])

In [57]:
ar3.reshape((6,5))

ValueError: cannot reshape array of size 12 into shape (6,5)

In [59]:
ar4=np.array([rd.randint(1,99) for i in range(100)])
ar4

array([89, 56, 24, 18, 35, 82, 12, 68, 35, 54, 79, 89, 25, 63, 98, 65, 40,
       12, 39, 41,  3,  2, 28, 94, 93, 18, 63, 23,  5, 78, 68, 56, 76, 31,
       70, 54, 39, 46, 54, 90, 20, 50, 58, 99, 88, 78, 64, 48, 93, 84, 73,
       85, 74, 37, 97, 94, 65, 98, 19, 16, 64, 11,  9, 16, 96, 20, 36, 29,
       99, 92,  5, 70, 90, 94, 41, 51, 53, 68, 23, 75, 30, 47, 29, 97, 28,
       94, 96, 91, 65, 86, 42, 46, 78, 28, 31, 90,  5, 86, 28, 95])

In [60]:
ar4.shape

(100,)

In [62]:
ar5=ar4.reshape((4,25))
ar5.shape

(4, 25)

In [64]:
ar6=ar4.reshape((4,5,5))
ar6.shape

(4, 5, 5)

In [65]:
ar6.ndim

3

In [66]:
ar6.reshape((100,))

array([89, 56, 24, 18, 35, 82, 12, 68, 35, 54, 79, 89, 25, 63, 98, 65, 40,
       12, 39, 41,  3,  2, 28, 94, 93, 18, 63, 23,  5, 78, 68, 56, 76, 31,
       70, 54, 39, 46, 54, 90, 20, 50, 58, 99, 88, 78, 64, 48, 93, 84, 73,
       85, 74, 37, 97, 94, 65, 98, 19, 16, 64, 11,  9, 16, 96, 20, 36, 29,
       99, 92,  5, 70, 90, 94, 41, 51, 53, 68, 23, 75, 30, 47, 29, 97, 28,
       94, 96, 91, 65, 86, 42, 46, 78, 28, 31, 90,  5, 86, 28, 95])

In [67]:
ar6.size

100

In [68]:
ar6.reshape((ar6.size,))

array([89, 56, 24, 18, 35, 82, 12, 68, 35, 54, 79, 89, 25, 63, 98, 65, 40,
       12, 39, 41,  3,  2, 28, 94, 93, 18, 63, 23,  5, 78, 68, 56, 76, 31,
       70, 54, 39, 46, 54, 90, 20, 50, 58, 99, 88, 78, 64, 48, 93, 84, 73,
       85, 74, 37, 97, 94, 65, 98, 19, 16, 64, 11,  9, 16, 96, 20, 36, 29,
       99, 92,  5, 70, 90, 94, 41, 51, 53, 68, 23, 75, 30, 47, 29, 97, 28,
       94, 96, 91, 65, 86, 42, 46, 78, 28, 31, 90,  5, 86, 28, 95])

In [69]:
ar6.flatten()

array([89, 56, 24, 18, 35, 82, 12, 68, 35, 54, 79, 89, 25, 63, 98, 65, 40,
       12, 39, 41,  3,  2, 28, 94, 93, 18, 63, 23,  5, 78, 68, 56, 76, 31,
       70, 54, 39, 46, 54, 90, 20, 50, 58, 99, 88, 78, 64, 48, 93, 84, 73,
       85, 74, 37, 97, 94, 65, 98, 19, 16, 64, 11,  9, 16, 96, 20, 36, 29,
       99, 92,  5, 70, 90, 94, 41, 51, 53, 68, 23, 75, 30, 47, 29, 97, 28,
       94, 96, 91, 65, 86, 42, 46, 78, 28, 31, 90,  5, 86, 28, 95])

In [72]:
ar8=ar4.reshape((2,2,5,5))
ar8.shape

(2, 2, 5, 5)

In [73]:
ar8.flatten()

array([89, 56, 24, 18, 35, 82, 12, 68, 35, 54, 79, 89, 25, 63, 98, 65, 40,
       12, 39, 41,  3,  2, 28, 94, 93, 18, 63, 23,  5, 78, 68, 56, 76, 31,
       70, 54, 39, 46, 54, 90, 20, 50, 58, 99, 88, 78, 64, 48, 93, 84, 73,
       85, 74, 37, 97, 94, 65, 98, 19, 16, 64, 11,  9, 16, 96, 20, 36, 29,
       99, 92,  5, 70, 90, 94, 41, 51, 53, 68, 23, 75, 30, 47, 29, 97, 28,
       94, 96, 91, 65, 86, 42, 46, 78, 28, 31, 90,  5, 86, 28, 95])

In [75]:
np_players=np.array([(74, 180), (74, 215), (72, 210), (72, 210), (73, 188), (69, 176), (69, 209), (71, 200), (76, 231), (71, 180), (73, 188), (73, 180), (74, 185), (74, 160), (69, 180), (70, 185), (73, 189), (75, 185), (78, 219), (79, 230), (76, 205), (74, 230), (76, 195), (72, 180), (71, 192), (75, 225), (77, 203), (74, 195), (73, 182), (74, 188), (78, 200), (73, 180), (75, 200), (73, 200), (75, 245), (75, 240), (74, 215), (69, 185), (71, 175), (74, 199), (73, 200), (73, 215), (76, 200), (74, 205), (74, 206), (70, 186), (72, 188), (77, 220), (74, 210), (70, 195), (73, 200), (75, 200), (76, 212), (76, 224), (78, 210), (74, 205), (74, 220), (76, 195), (77, 200), (81, 260), (78, 228), (75, 270), (77, 200), (75, 210), (76, 190), (74, 220), (72, 180), (72, 205), (75, 210), (73, 220), (73, 211), (73, 200), (70, 180), (70, 190), (70, 170), (76, 230), (68, 155), (71, 185), (72, 185), (75, 200), (75, 225), (75, 225), (75, 220), (68, 160), (74, 205), (78, 235), (71, 250), (73, 210), (76, 190), (74, 160), (74, 200), (79, 205), (75, 222), (73, 195), (76, 205), (74, 220), (74, 220), (73, 170), (72, 185), (74, 195), (73, 220), (74, 230), (72, 180), (73, 220), (69, 180), (72, 180), (73, 170), (75, 210), (75, 215), (73, 200), (72, 213), (72, 180), (76, 192), (74, 235), (72, 185), (77, 235), (74, 210), (77, 222), (75, 210), (76, 230), (80, 220), (74, 180), (74, 190), (75, 200), (78, 210), (73, 194), (73, 180), (74, 190), (75, 240), (76, 200), (71, 198), (73, 200), (74, 195), (76, 210), (76, 220), (74, 190), (73, 210), (74, 225), (70, 180), (72, 185), (73, 170), (73, 185), (73, 185), (73, 180), (71, 178), (74, 175), (74, 200), (72, 204), (74, 211), (71, 190), (74, 210), (73, 190), (75, 190), (75, 185), (79, 290), (73, 175), (75, 185), (76, 200), (74, 220), (76, 170), (78, 220), (74, 190), (76, 220), (72, 205), (74, 200), (76, 250), (74, 225), (75, 215), (78, 210), (75, 215), (72, 195), (74, 200), (72, 194), (74, 220), (70, 180), (71, 180), (70, 170), (75, 195), (71, 180), (71, 170), (73, 206), (72, 205), (71, 200), (73, 225), (72, 201), (75, 225), (74, 233), (74, 180), (75, 225), (73, 180), (77, 220), (73, 180), (76, 237), (75, 215), (74, 190), (76, 235), (75, 190), (73, 180), (71, 165), (76, 195), (75, 200), (72, 190), (71, 190), (77, 185), (73, 185), (74, 205), (71, 190), (72, 205), (74, 206), (75, 220), (73, 208), (72, 170), (75, 195), (75, 210), (74, 190), (72, 211), (74, 230), (71, 170), (70, 185), (74, 185), (77, 241), (77, 225), (75, 210), (75, 175), (78, 230), (75, 200), (76, 215), (73, 198), (75, 226), (75, 278), (79, 215), (77, 230), (76, 240), (71, 184), (75, 219), (74, 170), (69, 218), (71, 190), (76, 225), (72, 220), (72, 176), (70, 190), (72, 197), (73, 204), (71, 167), (72, 180), (71, 195), (73, 220), (72, 215), (73, 185), (74, 190), (74, 205), (72, 205), (75, 200), (74, 210), (74, 215), (77, 200), (75, 205), (73, 211), (72, 190), (71, 208), (74, 200), (77, 210), (75, 232), (75, 230), (75, 210), (78, 220), (78, 210), (74, 202), (76, 212), (78, 225), (76, 170), (70, 190), (72, 200), (80, 237), (74, 220), (74, 170), (71, 193), (70, 190), (72, 150), (71, 220), (74, 200), (71, 190), (72, 185), (71, 185), (74, 200), (69, 172), (76, 220), (75, 225), (75, 190), (76, 195), (73, 219), (76, 190), (73, 197), (77, 200), (73, 195), (72, 210), (72, 177), (77, 220), (77, 235), (71, 180), (74, 195), (74, 195), (73, 190), (78, 230), (75, 190), (73, 200), (70, 190), (74, 190), (72, 200), (73, 200), (73, 184), (75, 200), (75, 180), (74, 219), (76, 187), (73, 200), (74, 220), (75, 205), (75, 190), (72, 170), (73, 160), (73, 215), (72, 175), (74, 205), (78, 200), (76, 214), (73, 200), (74, 190), (75, 180), (70, 205), (75, 220), (71, 190), (72, 215), (78, 235), (75, 191), (73, 200), (73, 181), (71, 200), (75, 210), (77, 240), (72, 185), (69, 165), (73, 190), (74, 185), (72, 175), (70, 155), (75, 210), (70, 170), (72, 175), (72, 220), (74, 210), (73, 205), (74, 200), (76, 205), (75, 195), (80, 240), (72, 150), (75, 200), (73, 215), (74, 202), (74, 200), (73, 190), (75, 205), (75, 190), (71, 160), (73, 215), (75, 185), (74, 200), (74, 190), (72, 210), (74, 185), (74, 220), (74, 190), (73, 202), (76, 205), (75, 220), (72, 175), (73, 160), (73, 190), (73, 200), (72, 229), (72, 206), (72, 220), (72, 180), (71, 195), (75, 175), (75, 188), (74, 230), (73, 190), (75, 200), (79, 190), (74, 219), (76, 235), (73, 180), (74, 180), (74, 180), (72, 200), (74, 234), (74, 185), (75, 220), (78, 223), (74, 200), (74, 210), (74, 200), (77, 210), (70, 190), (73, 177), (74, 227), (73, 180), (71, 195), (75, 199), (71, 175), (72, 185), (77, 240), (74, 210), (70, 180), (77, 194), (73, 225), (72, 180), (76, 205), (71, 193), (76, 230), (78, 230), (75, 220), (73, 200), (78, 249), (74, 190), (79, 208), (75, 245), (76, 250), (72, 160), (75, 192), (75, 220), (70, 170), (72, 197), (70, 155), (74, 190), (71, 200), (76, 220), (73, 210), (76, 228), (71, 190), (69, 160), (72, 184), (72, 180), (69, 180), (73, 200), (69, 176), (73, 160), (74, 222), (74, 211), (72, 195), (71, 200), (72, 175), (72, 206), (76, 240), (76, 185), (76, 260), (74, 185), (76, 221), (75, 205), (71, 200), (72, 170), (71, 201), (73, 205), (75, 185), (76, 205), (75, 245), (71, 220), (75, 210), (74, 220), (72, 185), (73, 175), (73, 170), (73, 180), (73, 200), (76, 210), (72, 175), (76, 220), (73, 206), (73, 180), (73, 210), (75, 195), (75, 200), (77, 200), (73, 164), (72, 180), (75, 220), (70, 195), (74, 205), (72, 170), (80, 240), (71, 210), (71, 195), (74, 200), (74, 205), (73, 192), (75, 190), (76, 170), (73, 240), (77, 200), (72, 205), (73, 175), (77, 250), (76, 220), (71, 224), (75, 210), (73, 195), (74, 180), (77, 245), (71, 175), (72, 180), (73, 215), (69, 175), (73, 180), (70, 195), (74, 230), (76, 230), (73, 205), (73, 215), (75, 195), (73, 180), (79, 205), (74, 180), (73, 190), (74, 180), (77, 190), (75, 190), (74, 220), (73, 210), (77, 255), (73, 190), (77, 230), (74, 200), (74, 205), (73, 210), (77, 225), (74, 215), (77, 220), (75, 205), (77, 200), (75, 220), (71, 197), (74, 225), (70, 187), (79, 245), (72, 185), (72, 185), (70, 175), (74, 200), (74, 180), (72, 188), (73, 225), (72, 200), (74, 210), (74, 245), (76, 213), (82, 231), (74, 165), (74, 228), (70, 210), (73, 250), (73, 191), (74, 190), (77, 200), (72, 215), (76, 254), (73, 232), (73, 180), (72, 215), (74, 220), (74, 180), (71, 200), (72, 170), (75, 195), (74, 210), (74, 200), (77, 220), (70, 165), (71, 180), (73, 200), (76, 200), (71, 170), (75, 224), (74, 220), (72, 180), (76, 198), (79, 240), (76, 239), (73, 185), (76, 210), (78, 220), (75, 200), (76, 195), (72, 220), (72, 230), (73, 170), (73, 220), (75, 230), (71, 165), (76, 205), (70, 192), (75, 210), (74, 205), (75, 200), (73, 210), (71, 185), (71, 195), (72, 202), (73, 205), (73, 195), (72, 180), (69, 200), (73, 185), (78, 240), (71, 185), (73, 220), (75, 205), (76, 205), (70, 180), (74, 201), (77, 190), (75, 208), (79, 240), (72, 180), (77, 230), (73, 195), (75, 215), (75, 190), (75, 195), (73, 215), (73, 215), (76, 220), (77, 220), (75, 230), (70, 195), (71, 190), (71, 195), (75, 209), (74, 204), (69, 170), (70, 185), (75, 205), (72, 175), (75, 210), (73, 190), (72, 180), (72, 180), (72, 160), (76, 235), (75, 200), (74, 210), (69, 180), (73, 190), (72, 197), (72, 203), (75, 205), (77, 170), (76, 200), (80, 250), (77, 200), (76, 220), (79, 200), (71, 190), (75, 170), (73, 190), (76, 220), (77, 215), (73, 206), (76, 215), (70, 185), (75, 235), (73, 188), (75, 230), (70, 195), (69, 168), (71, 190), (72, 160), (72, 200), (73, 200), (70, 189), (70, 180), (73, 190), (76, 200), (75, 220), (72, 187), (73, 240), (79, 190), (71, 180), (72, 185), (74, 210), (74, 220), (74, 219), (72, 190), (76, 193), (76, 175), (72, 180), (72, 215), (71, 210), (72, 200), (72, 190), (70, 185), (77, 220), (74, 170), (72, 195), (76, 205), (71, 195), (76, 210), (71, 190), (73, 190), (70, 180), (73, 220), (73, 190), (72, 186), (71, 185), (71, 190), (71, 180), (72, 190), (72, 170), (74, 210), (74, 240), (74, 220), (71, 180), (72, 210), (75, 210), (72, 195), (71, 160), (72, 180), (72, 205), (72, 200), (72, 185), (74, 245), (74, 190), (77, 210), (75, 200), (73, 200), (75, 222), (73, 215), (76, 240), (72, 170), (77, 220), (75, 156), (72, 190), (71, 202), (71, 221), (75, 200), (72, 190), (73, 210), (73, 190), (71, 200), (70, 165), (75, 190), (71, 185), (76, 230), (73, 208), (68, 209), (71, 175), (72, 180), (74, 200), (77, 205), (72, 200), (76, 250), (78, 210), (81, 230), (72, 244), (73, 202), (76, 240), (72, 200), (72, 215), (74, 177), (76, 210), (73, 170), (76, 215), (75, 217), (70, 198), (71, 200), (74, 220), (72, 170), (73, 200), (76, 230), (76, 231), (73, 183), (71, 192), (68, 167), (71, 190), (71, 180), (74, 180), (77, 215), (69, 160), (72, 205), (76, 223), (75, 175), (76, 170), (75, 190), (76, 240), (72, 175), (74, 230), (76, 223), (74, 196), (72, 167), (75, 195), (78, 190), (77, 250), (70, 190), (72, 190), (79, 190), (74, 170), (71, 160), (68, 150), (77, 225), (75, 220), (71, 209), (72, 210), (70, 176), (72, 260), (72, 195), (73, 190), (72, 184), (74, 180), (72, 195), (72, 195), (75, 219), (72, 225), (73, 212), (74, 202), (72, 185), (78, 200), (75, 209), (72, 200), (74, 195), (75, 228), (75, 210), (76, 190), (74, 212), (74, 190), (73, 218), (74, 220), (71, 190), (74, 235), (75, 210), (76, 200), (74, 188), (76, 210), (76, 235), (73, 188), (75, 215), (75, 216), (74, 220), (68, 180), (72, 185), (75, 200), (71, 210), (70, 220), (72, 185), (73, 231), (72, 210), (75, 195), (74, 200), (70, 205), (76, 200), (71, 190), (82, 250), (72, 185), (73, 180), (74, 170), (71, 180), (75, 208), (77, 235), (72, 215), (74, 244), (72, 220), (73, 185), (78, 230), (77, 190), (73, 200), (73, 180), (73, 190), (73, 196), (73, 180), (76, 230), (75, 224), (70, 160), (73, 178), (72, 205), (73, 185), (75, 210), (74, 180), (73, 190), (73, 200), (76, 257), (73, 190), (75, 220), (70, 165), (77, 205), (72, 200), (77, 208), (74, 185), (75, 215), (75, 170), (75, 235), (75, 210), (72, 170), (74, 180), (71, 170), (76, 190), (71, 150), (75, 230), (76, 203), (83, 260), (75, 246), (74, 186), (76, 210), (72, 198), (72, 210), (75, 215), (75, 180), (72, 200), (77, 245), (73, 200), (72, 192), (70, 192), (74, 200), (72, 192), (74, 205), (72, 190), (71, 186), (70, 170), (71, 197), (76, 219), (74, 200), (76, 220), (74, 207), (74, 225), (74, 207), (75, 212), (75, 225), (71, 170), (71, 190), (74, 210), (77, 230), (71, 210), (74, 200), (75, 238), (77, 234), (76, 222), (74, 200), (76, 190), (72, 170), (71, 220), (72, 223), (75, 210), (73, 215), (68, 196), (72, 175), (69, 175), (73, 189), (73, 205), (75, 210), (70, 180), (70, 180), (74, 197), (75, 220), (74, 228), (74, 190), (73, 204), (74, 165), (75, 216), (77, 220), (73, 208), (74, 210), (76, 215), (74, 195), (75, 200), (73, 215), (76, 229), (78, 240), (75, 207), (73, 205), (77, 208), (74, 185), (72, 190), (74, 170), (72, 208), (71, 225), (73, 190), (75, 225), (73, 185), (67, 180), (67, 165), (76, 240), (74, 220), (73, 212), (70, 163), (75, 215), (70, 175), (72, 205), (77, 210), (79, 205), (78, 208), (74, 215), (75, 180), (75, 200), (78, 230), (76, 211), (75, 230), (69, 190), (75, 220), (72, 180), (75, 205), (73, 190), (74, 180), (75, 205), (75, 190), (73, 195)]
)

In [76]:
np_skills=np.array(['Keeper', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Bowler', 'Bowler', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Keeper', 'Keeper', 'Keeper', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Keeper', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Bowler', 'Bowler', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper', 'Batsman', 'Keeper', 'Bowler', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Bowler', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Batsman', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Bowler', 'Bowler', 'Bowler', 'Batsman', 'Keeper', 'Bowler', 'Bowler', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Batsman', 'Bowler', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper', 'Keeper', 'Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Batsman', 'Bowler', 'Keeper', 'Keeper', 'Batsman', 'Bowler', 'Bowler', 'Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Bowler', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Batsman', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Batsman', 'Batsman', 'Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Keeper', 'Bowler', 'Keeper', 'Bowler', 'Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Batsman', 'Keeper', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Batsman', 'Bowler', 'Keeper', 'Bowler', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Bowler', 'Bowler', 'Bowler', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Batsman', 'Bowler', 'Keeper', 'Bowler', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Batsman', 'Batsman', 'Keeper', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Bowler', 'Batsman', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Bowler', 'Bowler', 'Keeper', 'Bowler', 'Keeper', 'Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Bowler', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Batsman', 'Batsman', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Batsman', 'Batsman', 'Bowler', 'Batsman', 'Keeper', 'Bowler', 'Bowler', 'Keeper', 'Bowler', 'Bowler', 'Keeper', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Keeper-Batsman', 'Keeper-Batsman', 'Bowler', 'Bowler', 'Bowler', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman']
)

In [77]:
np_players.size,np_players.shape,np_players.ndim,np_players.dtype

(2030, (1015, 2), 2, dtype('int32'))

In [78]:
np_skills.size,np_skills.shape,np_skills.ndim,np_skills.dtype

(1015, (1015,), 1, dtype('<U14'))

In [79]:
np_skills[0]

'Keeper'

In [80]:
np_skills[-1]

'Keeper-Batsman'

In [81]:
np_skills[:5]

array(['Keeper', 'Batsman', 'Bowler', 'Keeper-Batsman', 'Batsman'],
      dtype='<U14')

In [82]:
np_skills[-5:]

array(['Keeper', 'Keeper-Batsman', 'Batsman', 'Bowler', 'Keeper-Batsman'],
      dtype='<U14')

    We want players who are in even position

In [ ]:
np_skills[::2]

In [ ]:
np_skills[1::2]

In [98]:
cond_keeper=np_skills=='Keeper'

In [100]:
np_skills[cond_keeper].size

141

In [93]:
lst2=[1,2,3,2,4]
for i in lst2:
    print(i==2)

False
True
False
True
False


In [94]:
np_lst2=np.array(lst2)
np_lst2

array([1, 2, 3, 2, 4])

In [96]:
cond=np_lst2==2
cond

array([False,  True, False,  True, False])

In [97]:
np_lst2[cond]

array([2, 2])

    Whenever we apply condition for slicing it is going to return where our condition is true

    how many batsman are there in the array

In [101]:
cond_batsman=np_skills=='Batsman'
cond_batsman

array([False,  True, False, ...,  True, False, False])

In [103]:
np_skills[cond_batsman].size

323

    what percentage of batsman we have in array

In [106]:
round((np_skills[cond_batsman].size/np_skills.size)*100,2)

31.82

In [107]:
cond_bats_keeper=np_skills=='Keeper-Batsman'

In [109]:
np_skills[cond_bats_keeper].size+np_skills[cond_batsman].size

668

    and  &
    or   |

In [113]:
(np_skills[cond_batsman | cond_bats_keeper].size/np_skills.size)*100

65.8128078817734

In [114]:
np_players.ndim

2

In [116]:
lst3=[
    [1,2],
    [3,4]
]
lst3

[[1, 2], [3, 4]]

In [119]:
lst3[1][0]

3

In [120]:
np_players[0][0]

74

In [121]:
np_players[0][1]

180

    We want to create a array which will store only heights of the players

In [135]:
np_height=np_players[:,0]
np_height

array([74, 74, 72, ..., 75, 75, 73])

In [126]:
np_players.shape

(1015, 2)

    np.array()
    np_players[rows,columns]

In [132]:
np_players[0]

array([ 74, 180])

In [133]:
np_players[:,1]

array([180, 215, 210, ..., 205, 190, 195])

In [138]:
np_height_cms=np_players[:,0]*2.54
np_height_cms

array([187.96, 187.96, 182.88, ..., 190.5 , 190.5 , 185.42])

    (74, 180), 
    (74, 215), 
    (72, 210), 
    (72, 210), 
    (73, 188),

In [139]:
np_players[0]

array([ 74, 180])

In [140]:
np_players[0,0]

74

In [141]:
np_players[2,0]

72

In [142]:
np_players[1,1]

215

    range(start,end,step)

In [150]:
np_players[:,0]

array([74, 74, 72, ..., 75, 75, 73])

In [145]:
lst5=[rd.randint(1,15) for i in range(50)]
lst5[:5]

[5, 6, 6, 15, 4]

In [154]:
np_weight_kg=np_players[:,1]*0.453592
np_weight_kg

array([81.64656, 97.52228, 95.25432, ..., 92.98636, 86.18248, 88.45044])

In [155]:
np_weight_kg[:5]

array([81.64656 , 97.52228 , 95.25432 , 95.25432 , 85.275296])

In [156]:
np_weight_kg[-5:]

array([86.18248, 81.64656, 92.98636, 86.18248, 88.45044])

In [158]:
np_players_new=np_players.copy()
np_players_new

array([[ 74, 180],
       [ 74, 215],
       [ 72, 210],
       ...,
       [ 75, 205],
       [ 75, 190],
       [ 73, 195]])

In [160]:
np_players_new[:,0]=np_players_new[:,0]*2.54

In [161]:
np_players_new

array([[187, 180],
       [187, 215],
       [182, 210],
       ...,
       [190, 205],
       [190, 190],
       [185, 195]])

In [162]:
np_players_new[:,1]=np_players_new[:,1]*0.453592

In [163]:
np_players_new

array([[187,  81],
       [187,  97],
       [182,  95],
       ...,
       [190,  92],
       [190,  86],
       [185,  88]])

    What percentage of players have height greater than 190cms and weight is less than 100

In [170]:
cond_height_190=np_players_new[:,0]>190
cond_weight_100=np_players_new[:,1]<100

In [164]:
np_players_new

array([[187,  81],
       [187,  97],
       [182,  95],
       ...,
       [190,  92],
       [190,  86],
       [185,  88]])

In [174]:
round((np_players_new[cond_height_190 & cond_weight_100].size/np_players_new.size)*100,2)

12.32

    Get the percentage of players whose height is between 150,200 and weight is between 100 and 120

    height >= 150
    height <=200

    weight >=100
    weight <=120

In [175]:
cond_ht_150=np_players_new[:,0]>=150
cond_ht_200=np_players_new[:,0]<=200
cond_kg_100=np_players_new[:,1]>=100
cond_kg_120=np_players_new[:,1]<=120

    select salary 
    from emp
    where salary between 1000 and 1500

In [176]:
cond_all=cond_ht_150 & cond_ht_200 & cond_kg_100 & cond_kg_120
cond_all

array([False, False, False, ..., False, False, False])

In [179]:
np_players_new[cond_all].size/np_players_new.size

0.1399014778325123

In [182]:
np_players_new[(np_players_new[:,0]>=150) & (np_players_new[:,0]<=200) & (np_players_new[:,1]>=100) & (np_players_new[:,1]<=120)].size/np_players_new.size

0.1399014778325123

In [1]:
import numpy as np

In [2]:
arr_1 = np.array([1, 2, 3,4,5,9])
arr_2 = np.array([6,7,8,9,10,20])
arr_1

array([1, 2, 3, 4, 5, 9])

In [3]:
arr_2

array([ 6,  7,  8,  9, 10, 20])

In [187]:
np.hstack((arr_1,arr_2,arr_2))

array([ 1,  2,  3,  4,  5,  9,  6,  7,  8,  9, 10, 20,  6,  7,  8,  9, 10,
       20])

In [4]:
np.vstack((arr_1,arr_2,arr_1))

array([[ 1,  2,  3,  4,  5,  9],
       [ 6,  7,  8,  9, 10, 20],
       [ 1,  2,  3,  4,  5,  9]])

In [6]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [7]:
np.concatenate((arr1,arr2),axis=0)

array([1, 2, 3, 4, 5, 6])

In [8]:
np.concatenate((arr1,arr2),axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [9]:
arr1 = np.array([
    [1, 2],
    [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

In [10]:
arr1

array([[1, 2],
       [3, 4]])

In [202]:
arr2

array([[5, 6],
       [7, 8]])

    axis=1=> horizontal 
    axis=0 => vertical

In [199]:
np.concatenate((arr1,arr2),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [200]:
np.concatenate((arr1,arr2),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [203]:
arr_8=np.array([3,5,4,9,8,7,4,5])
arr_8

array([3, 5, 4, 9, 8, 7, 4, 5])

In [204]:
arr_8.sort()

In [205]:
arr_8

array([3, 4, 4, 5, 5, 7, 8, 9])

In [206]:
arr_8.sort(reversed=True)

TypeError: sort() got an unexpected keyword argument 'reversed'