    Recap
        Numpy
            Creation
            Slicing
                One dimensional Slicing
                n dimension slicing also
            Properties
                size
                shape
                ndim
                dtype
            reshape()
            flatten()
            hstack()
            vstack()
            concatenation
                axis=0
                axis=1
            sort()

            Special Types of numpy array

In [1]:
import numpy as np  
import random as rd

In [31]:
ar1=np.array([rd.randint(10,99) for i in range(12)])
ar1

array([56, 12, 68, 45, 18, 12, 47, 60, 46, 44, 14, 59])

In [5]:
ar2=ar1.reshape((2,2,3,1))

In [30]:
ar2.flatten()

array([16, 71, 90, 19, 74, 91, 31, 75, 93, 33, 86, 95])

In [32]:
ar3=ar1.reshape((4,3))
ar3

array([[56, 12, 68],
       [45, 18, 12],
       [47, 60, 46],
       [44, 14, 59]])

In [34]:
ar3.sort(axis=0)

In [35]:
ar3

array([[44, 12, 12],
       [45, 14, 46],
       [47, 18, 59],
       [56, 60, 68]])

    axis=1 => hor
    axis=0 => vertical

In [36]:
ar3.sort(axis=1)

In [37]:
ar3

array([[12, 12, 44],
       [14, 45, 46],
       [18, 47, 59],
       [56, 60, 68]])

In [38]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [39]:
arr.shape

(6, 2)

In [40]:
newarr = np.array_split(arr, 3)
newarr

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

In [41]:
np.array_split(arr,4)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10]]),
 array([[11, 12]])]

In [42]:
np.array_split(arr,2)

[array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])]

    Arithmatic
        addition
        subtraction
        multiplication
        division

In [2]:
lst1=[1,2,3]
lst2=[5,6,7]
lst1+lst2

[1, 2, 3, 5, 6, 7]

In [3]:
ar1=np.array([1,2,5])
ar2=np.array([5,7,9])
ar1+ar2

array([ 6,  9, 14])

In [10]:
np.add(ar1,ar2)

array([ 6,  9, 14])

In [4]:
ar1-ar2

array([-4, -5, -4])

In [11]:
np.subtract(ar1,ar2)

array([-4, -5, -4])

In [5]:
ar1*ar2

array([ 5, 14, 45])

In [12]:
np.multiply(ar1,ar2)

array([ 5, 14, 45])

In [6]:
ar1/ar2

array([0.2       , 0.28571429, 0.55555556])

In [13]:
np.divide(ar1,ar2)

array([0.2       , 0.28571429, 0.55555556])

    % => Remainder

In [7]:
ar1%ar2

array([1, 2, 5])

In [16]:
np.mod(ar1,ar2)

array([1, 2, 5])

In [8]:
ar1//ar2

array([0, 0, 0])

In [14]:
np.floor_divide(ar1,ar2)

array([0, 0, 0])

In [9]:
ar2//ar1

array([5, 3, 1])

In [15]:
np.floor_divide(ar2,ar1)

array([5, 3, 1])

    Arithmatic operators/Functions
        np.add()            =>  +
        np.subtract()       =>  -
        np.multiply()       =>  *
        np.divide()         =>  /
        np.floor_divide()   =>  //
        np.mod()            =>  %
        np.power()

In [17]:
ar1**ar2

array([      1,     128, 1953125])

In [19]:
ar1,ar2

(array([1, 2, 5]), array([5, 7, 9]))

In [18]:
np.power(ar1,ar2)

array([      1,     128, 1953125])

In [21]:
ar5=np.array([i for i in range(5)])
ar5

array([0, 1, 2, 3, 4])

In [20]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [22]:
np.arange(5,6)

array([5])

In [23]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

    pandas
        c
        python

    modin.pandas
    pyarrow
    pyspark

    Create a numpy array of 10 elements which will contain multiples of 5

In [24]:
np.arange(5,51,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [25]:
np.arange(7,71,7)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

    Pythagoras
        h2=p2+b2

In [26]:
np.sin(0)

0.0

In [27]:
np.sin(90)

0.8939966636005579

In [29]:
np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [ ]:
-1

In [30]:
np.absolute([-1,-5,-6])

array([1, 5, 6])

    np_players
    np_skills
        condition
        single
        consecutive

    Statistical 
        Measure of Central Tendency
            mean
            median
            mode
        Measure of Dispersion / Spread
            range
                max
                min
            variance
            SD
            Quartile
            Percentile
            IQR
            Covariance
        Measure of Symmetry
            Skewness
            Kurtosis  

In [31]:
np_height=np.array([rd.randrange(90,200) for i in range(100)])
np_height

array([133, 171, 131, 128, 188, 130, 172, 154, 140,  97, 159, 171, 180,
       185, 182, 112, 102, 182, 168, 182, 120, 143, 118, 167, 160,  98,
       149, 126, 175, 105, 166, 148, 163, 139, 123, 141, 183, 101, 104,
       181,  95, 103, 147, 132, 154, 189, 159, 109, 129, 101, 130, 153,
       101, 118, 122, 139, 127, 152, 172, 139, 117, 118,  95, 136, 111,
       190, 131,  94, 113, 130, 184, 141, 179, 136, 143, 175, 166, 152,
       113, 122, 174, 112, 123,  96, 117, 120, 153, 117, 124, 170, 164,
       124, 172, 134, 123, 149, 118, 113, 110, 113])

In [32]:
np.max(np_height)

190

In [33]:
np.min(np_height)

94

In [34]:
np.max(np_height)-np.min(np_height)

96

In [36]:
np.mean(np_height)

139.2

In [37]:
np.median(np_height)

135.0

In [50]:
np.std(np_height)

27.45432570652574

In [51]:
np.var(np_height)

753.7400000000001

In [52]:
np.cov(np_height)

array(761.35353535)

    Q1  25th 
    Q2  50th
    Q3  75th
    Q4  100th

In [42]:
q1=np.quantile(np_height,0.25)
q2=np.quantile(np_height,0.50)
q3=np.quantile(np_height,0.75)
q4=np.quantile(np_height,1)
q1,q2,q3,q4

(117.75, 135.0, 164.5, 190)

In [46]:
q1=np.percentile(np_height,25)
q2=np.percentile(np_height,50)
q3=np.percentile(np_height,75)
q4=np.percentile(np_height,100)
q1,q2,q3,q4

(117.75, 135.0, 164.5, 190.0)

    IQR
        Q3-Q1
    lower_outlier_gate = q1 - 1.5*iqr
    upper_outlier_gate = q3 + 1.5*iqr

In [48]:
iqr=q3-q1
iqr

46.75

In [49]:
lower_outlier_gate = q1 - 1.5*iqr
upper_outlier_gate = q3 + 1.5*iqr
lower_outlier_gate,upper_outlier_gate

(47.625, 234.625)

In [54]:
np.corrcoef(np_height)

array([[1., 1.],
       [1., 1.]])

    Aggregation    

In [55]:
np.sum(np_height)

13920

In [58]:
np_height.size

100

In [59]:
x=np.array([1,2,3,4,70,6])
print(np.add.reduce(x))
print(x.sum())

86
86


In [62]:
print(np.add.accumulate(x))

[ 1  3  6 10 80 86]


In [63]:
print(np.cumsum(x))

[ 1  3  6 10 80 86]


You are provided with 2 lists that contain the data of an ecommerce website. The first list contains the data for the number of items sold for a particular product and the second list contains the price of the product sold. As a part of this exercise, solve the questions that are provided below.

In [64]:
np_qty=np.array([8, 9, 9, 1, 6, 9, 5, 7, 3, 9, 7, 3, 4, 8, 3, 5, 8, 4, 8, 7, 5, 7, 3, 6, 1, 2, 7, 4, 7, 7, 8, 4, 3, 4, 2, 2, 2, 7, 3, 5, 6, 1, 1, 3, 2, 1, 1, 7, 7, 1, 4, 4, 5, 6, 1, 2, 7, 4, 5, 8, 1, 4, 8, 6, 2, 4, 3, 7, 3, 6, 2, 3, 3, 3, 2, 4, 6, 8, 9, 3, 9, 3, 1, 8, 6, 6, 3, 3, 9, 4, 6, 4, 9, 6, 7, 1, 2, 8, 7, 8, 1, 4])

In [65]:
np_price=np.array([195, 225, 150, 150, 90, 60, 75, 255, 270, 225, 135, 195, 30, 15, 210, 105, 15, 30, 180, 60, 165, 60, 45, 225, 180, 90, 30, 210, 150, 15, 270, 60, 210, 180, 60, 225, 150, 150, 120, 195, 75, 240, 60, 45, 30, 180, 240, 285, 135, 165, 180, 240, 60, 105, 165, 240, 120, 45, 120, 165, 285, 225, 90, 105, 225, 45, 45, 45, 75, 180, 90, 240, 30, 30, 60, 135, 180, 15, 255, 180, 270, 135, 105, 135, 210, 180, 135, 195, 225, 75, 225, 15, 240, 60, 15, 180, 255, 90, 15, 150, 230, 150])

    Calculate the Sale for each product

In [66]:
np_price.size

102

In [67]:
np_sales=np_price*np_qty
np_sales

array([1560, 2025, 1350,  150,  540,  540,  375, 1785,  810, 2025,  945,
        585,  120,  120,  630,  525,  120,  120, 1440,  420,  825,  420,
        135, 1350,  180,  180,  210,  840, 1050,  105, 2160,  240,  630,
        720,  120,  450,  300, 1050,  360,  975,  450,  240,   60,  135,
         60,  180,  240, 1995,  945,  165,  720,  960,  300,  630,  165,
        480,  840,  180,  600, 1320,  285,  900,  720,  630,  450,  180,
        135,  315,  225, 1080,  180,  720,   90,   90,  120,  540, 1080,
        120, 2295,  540, 2430,  405,  105, 1080, 1260, 1080,  405,  585,
       2025,  300, 1350,   60, 2160,  360,  105,  180,  510,  720,  105,
       1200,  230,  600])

    Calculate the no of products which are price between 100 and 150

In [68]:
cond_100=np_price>=100
cond_150=np_price<=150

In [70]:
np_price[cond_100 & cond_150].size

20

In [71]:
np.sum(np_qty)

490

In [72]:
np.mean(np_price)

139.01960784313727

In [73]:
np.max(np_price)

285

In [74]:
np.sum(np_sales)

67100

In [75]:
np_qty[19]

7

In [76]:
np_qty[49]

1

    How many products fall under the category of expensive goods? 
    An expensive good is that good whose price is more than the average price of the products sold by the company.

In [78]:
avg=np.mean(np_price)
avg

139.01960784313727

In [82]:
cond_avg=np_price>avg

In [81]:
np_price[cond_avg].size

52

In [83]:
np_coef=np.array([[7,5,-3],[3,-5,2],[5,3,-7]])
np_coef

array([[ 7,  5, -3],
       [ 3, -5,  2],
       [ 5,  3, -7]])

In [84]:
np_constant=np.array([16,-8,0])

In [85]:
np.linalg.solve(np_coef,np_constant)

array([1., 3., 2.])

In [1]:
import numpy as np

In [2]:
np_coe=np.array([
    [-4,7,-3],
    [1,-2,1],
    [-3,5,-1]
])
np_const=np.array([2,3,-4])

In [4]:
np_res=np.linalg.solve(np_coe,np_const)
np_res

array([-34., -23.,  -9.])

In [6]:
np_res2=np_coe*np_res
np_res2

array([[ 136., -161.,   27.],
       [ -34.,   46.,   -9.],
       [ 102., -115.,    9.]])

In [8]:
np.add.reduce(np_res2,axis=1)

array([ 2.,  3., -4.])

In [ ]:
np_res2

In [9]:
np_ar=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [10]:
np.sum(np_ar)

45

In [15]:
np.add.reduce(np_ar,axis=1)

array([ 6, 15, 24])

In [13]:
np.add.reduce(np_ar.flatten())

45

In [18]:
np.subtract.reduce(np_ar,axis=1)

array([ -4,  -7, -10])

In [19]:
np.subtract.reduce(np_ar,axis=0)

array([-10, -11, -12])

In [21]:
np.multiply.reduce(np_ar,axis=1)

array([  6, 120, 504])

In [ ]:
print()

    The following ways are commonly used:

    * np.array():
    * np.arange(): Create array with increments of a fixed step size
    * np.ones(): Create array of 1s
    * np.zeros(): Create array of 0s
    * np.linspace(): Create array of fixed length
    * np.full(): Create a constant array of any number ‘n’
    * np.tile(): Create a new array by repeating an existing array for a particular number of times
    * np.eye(): Create an identity matrix of any dimension
    * np.random.random(): Create array of random numbers between 0 and 1
    * np.random.randint(): Create a random array of integers within a particular range

In [22]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [23]:
np.arange(10,5,-1)

array([10,  9,  8,  7,  6])

In [24]:
np.ones()

TypeError: ones() missing 1 required positional argument: 'shape'

In [25]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [26]:
np.ones((2,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [27]:
np.ones((2,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [28]:
np.zeros()

TypeError: zeros() missing required argument 'shape' (pos 0)

In [29]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.zeros((2,5),dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [31]:
np.linspace()

TypeError: linspace() missing 2 required positional arguments: 'start' and 'stop'

In [35]:
np_lin=np.linspace(10,20)

In [36]:
np_lin[0]

10.0

In [37]:
np_lin[1]

10.204081632653061

In [38]:
np_lin[2]

10.408163265306122

In [39]:
np_lin[1]-np_lin[0]

0.204081632653061

In [40]:
np_lin[2]-np_lin[1]

0.204081632653061

In [48]:
np.arange(5,10,2)

array([5, 7, 9])

In [50]:
np.linspace(2,6,3)

array([2., 4., 6.])

In [49]:
np.linspace(2,6,3,retstep=True)

(array([2., 4., 6.]), 2.0)

In [44]:
np.full(5,45)

array([45, 45, 45, 45, 45])

In [45]:
np.full((5,7),9)

array([[9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9]])

In [46]:
np.full((2,2,7),'a')

array([[['a', 'a', 'a', 'a', 'a', 'a', 'a'],
        ['a', 'a', 'a', 'a', 'a', 'a', 'a']],

       [['a', 'a', 'a', 'a', 'a', 'a', 'a'],
        ['a', 'a', 'a', 'a', 'a', 'a', 'a']]], dtype='<U1')

In [47]:
np.full((5,5),0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [51]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [54]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [73]:
np.random.random()

0.7348831914911019

In [118]:
np.random.randint(5,66,(2,6))

array([[14, 43, 64, 41,  7, 32],
       [36, 20, 11, 61, 41, 64]])

    creation
        np.array()
        np.arange()
        np.random.randint()

    Slicing
        single 
        consecutive
        condition

    Arithmatic/Statistical
        sum
        max
        min
        mean
        add
        add.reduce
    Linalgebra
    matrix
        dot product
        inv
        determinant
    Special array
        zeros
        ones
